#!/usr/bin/env python3
"""Crea las 24 actividades nuevas del rango 3-5 (ids 3a5-13 .. 3a5-36)."""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
DST = ROOT / "data" / "activities"

A = [
 dict(n=13, slug="lampara-lava", tipo="experimento",
  titulo="Lámpara de lava casera",
  gancho="Burbujas de color que suben y bajan como en una lámpara mágica.",
  duracion="20 min", dp=1, dm=2,
  materiales=["Un frasco o botella alto y transparente","Aceite vegetal","Agua","Colorante de alimentos","Una pastilla efervescente"],
  preparacion="Reúne todo sobre una bandeja por si se derrama. Llena el frasco con un tercio de agua.",
  pasos=["Echa agua hasta un tercio del frasco y agrega unas gotas de colorante.","Completa casi hasta arriba con aceite y observen cómo se separan.","Pregunta qué creen que pasará antes de seguir.","Parte una pastilla efervescente y déjala caer dentro.","Observen las burbujas de color subir y bajar; añadan otro trozo para repetir."],
  aprendizaje="Muestra de forma visual que el aceite y el agua no se mezclan y que el gas empuja el color hacia arriba. Despierta la curiosidad y el gusto por preguntarse «¿por qué?».",
  variantes="Apaguen la luz y alumbren el frasco por detrás con una linterna para un efecto espectacular.",
  seguridad="La pastilla efervescente no se come; un adulto la maneja y supervisa todo el experimento."),

 dict(n=14, slug="flores-color", tipo="experimento",
  titulo="Flores que cambian de color",
  gancho="Una flor blanca que amanece azul o roja: la planta bebe colores.",
  duracion="15 min + espera", dp=1, dm=2,
  materiales=["Flores blancas (clavel) o un tallo de apio con hojas","Vasos con agua","Colorante de alimentos"],
  preparacion="Prepara un vaso de agua por cada color y disuelve bastante colorante en cada uno.",
  pasos=["Pongan colorante en cada vaso y remuevan hasta teñir el agua.","Recorten un poco la base del tallo y métanlo en un vaso.","Predigan qué color tomará la flor.","Dejen reposar varias horas o toda la noche.","Observen al día siguiente cómo los pétalos se tiñeron del color del agua."],
  aprendizaje="Demuestra cómo las plantas absorben agua por el tallo hasta las hojas y flores. Esperar y observar el cambio enseña paciencia y método científico.",
  variantes="Partan el tallo a lo largo y pongan cada mitad en un color distinto para una flor de dos tonos.",
  seguridad="Un adulto recorta los tallos; el agua con colorante no se bebe."),

 dict(n=15, slug="globo-bicarbonato", tipo="experimento",
  titulo="El globo que se infla solo",
  gancho="Mezclar dos ingredientes de la cocina y… ¡el globo se infla como por arte de magia!",
  duracion="15 min", dp=2, dm=2,
  materiales=["Una botella de plástico","Vinagre","Bicarbonato de sodio","Un globo","Un embudo o cuchara"],
  preparacion="Pon un par de dedos de vinagre en la botella. Con el embudo, llena un tercio del globo con bicarbonato.",
  pasos=["Calza la boca del globo en el cuello de la botella sin que caiga el bicarbonato.","Pregunta qué pasará al juntar los dos ingredientes.","Levanten el globo para que el bicarbonato caiga dentro del vinagre.","Observen la espuma y cómo el globo se infla solo.","Cuenten en voz alta mientras el globo crece."],
  aprendizaje="Introduce las reacciones químicas: el vinagre y el bicarbonato producen un gas que infla el globo. Predecir y comprobar es la esencia de pensar como científico.",
  variantes="Prueben con más o menos bicarbonato y comparen cuánto se infla cada globo.",
  seguridad="Un adulto maneja el vinagre y supervisa; no acercar la cara a la botella al reaccionar."),

 dict(n=16, slug="flota-hunde", tipo="experimento",
  titulo="¿Flota o se hunde?",
  gancho="Un detective del agua que predice qué objetos nadan y cuáles se van al fondo.",
  duracion="20 min", dp=1, dm=1,
  materiales=["Un balde o palangana con agua","Objetos variados (corcho, piedra, cuchara, esponja, juguete, tapa)","Una toalla"],
  preparacion="Llena el recipiente con agua y reúne objetos de distintos materiales y pesos.",
  pasos=["Tomen un objeto y pregunten: «¿flotará o se hundirá?».","Que el niño haga su predicción antes de soltarlo.","Suéltenlo en el agua y comprueben qué pasó.","Separen en dos grupos: los que flotan y los que se hunden.","Al final, observen qué tienen en común los que flotan."],
  aprendizaje="Explora las nociones de peso, material y flotación a través de la predicción y la comprobación. Clasificar resultados desarrolla el razonamiento.",
  variantes="Prueben si un trozo de plastilina se hunde, y luego si flota al darle forma de barquito.",
  seguridad="Supervisa siempre el juego con agua y seca el suelo para evitar resbalones."),

 dict(n=17, slug="caja-semola", tipo="sensorial",
  titulo="Mesa de exploración de sémola",
  gancho="Una bandeja llena de sémola para escarbar, enterrar y descubrir tesoros.",
  duracion="20-30 min", dp=1, dm=1,
  materiales=["Una bandeja o caja baja","Sémola, harina o arena fina","Cucharas, vasos, embudos y juguetitos","Un mantel para el suelo"],
  preparacion="Vierte la sémola en la bandeja y reparte alrededor cucharas, vasos y objetos para esconder.",
  pasos=["Pon un mantel en el suelo y la bandeja encima para contener el desorden.","Esconde algunos juguetitos en la sémola para que los busque.","Deja que escarbe, trasvase y haga montañas a su gusto.","Acompaña nombrando texturas y acciones: «llenas», «vacías», «entierras».","Al terminar, invítalo a ayudar a recoger con una escobilla."],
  aprendizaje="Estimula el tacto y la motricidad fina al pellizcar, verter y cavar. El juego libre con material suelto favorece la concentración y la calma.",
  variantes="Cambien la sémola por arroz teñido de colores o por arena para variar la experiencia.",
  seguridad="Supervisa para que no se la lleve a la boca ni a los ojos; recoge lo que caiga al suelo."),

 dict(n=18, slug="pintura-inflada", tipo="sensorial",
  titulo="Pintura que se infla",
  gancho="Una pintura esponjosa que queda en relieve, como nubes de colores.",
  duracion="20 min", dp=2, dm=2,
  materiales=["Espuma de afeitar","Pegamento blanco","Colorante o témpera","Cartón grueso","Cucharas para mezclar"],
  preparacion="Mezcla en partes iguales espuma de afeitar y pegamento, y reparte en bols con un color distinto cada uno.",
  pasos=["Muéstrale la mezcla esponjosa y deja que la toque.","Pinten sobre el cartón con cucharas, pinceles o los dedos.","Hagan formas con relieve: nubes, helados, montañas.","Observen cómo la pintura queda inflada y blandita al secar.","Dejen secar la obra unas horas para que mantenga el volumen."],
  aprendizaje="Combina arte y experiencia sensorial: la textura inflada es nueva y fascinante. Mezclar y crear desarrolla la creatividad y la coordinación.",
  variantes="Agreguen purpurina a la mezcla o dibujen primero un contorno para rellenar.",
  seguridad="Vigila que no se lleve la espuma a la boca y protege la ropa con un delantal."),

 dict(n=19, slug="adivina-sonido", tipo="sensorial",
  titulo="Adivina el sonido",
  gancho="Frascos que suenan distinto según lo que esconden: ¿adivinas qué hay dentro?",
  duracion="15-20 min", dp=2, dm=1,
  materiales=["Frascos o envases opacos iguales","Rellenos variados (arroz, porotos, monedas, agua, algodón)","Cinta para sellar"],
  preparacion="Prepara pares de frascos con el mismo relleno, ciérralos bien y mézclalos.",
  pasos=["Agita un frasco y escuchen juntos el sonido que hace.","Pídele que adivine qué hay dentro por cómo suena.","Agiten otros frascos y comparen fuerte, suave, seco o líquido.","Jueguen a encontrar las parejas que suenan igual.","Abran los frascos al final para comprobar las respuestas."],
  aprendizaje="Afina la atención auditiva y la capacidad de comparar y deducir. Buscar parejas por el sonido entrena la memoria y la concentración.",
  variantes="Háganlo con instrumentos o con objetos de la casa escondidos tras una tela.",
  seguridad="Sella muy bien los frascos; supervisa los que contienen objetos pequeños."),

 dict(n=20, slug="rayuela", tipo="recreativa",
  titulo="La rayuela",
  gancho="Saltar de casilla en casilla en un clásico de siempre que nunca pasa de moda.",
  duracion="20-30 min", dp=1, dm=1,
  materiales=["Tiza para el suelo o cinta de papel para interior","Una piedra plana o un saquito"],
  preparacion="Dibujen juntos la rayuela en el suelo con casillas numeradas del 1 al 10.",
  pasos=["Repasen juntos los números de cada casilla en voz alta.","El niño lanza la piedra a la casilla número uno.","Salta las casillas a la pata coja, saltándose la que tiene la piedra.","Al volver, recoge la piedra y avanza al número siguiente.","Continúen turnándose hasta completar el recorrido."],
  aprendizaje="Desarrolla el equilibrio, la coordinación y el salto a la pata coja. Reconocer números y respetar turnos suma aprendizaje matemático y social.",
  variantes="Reemplacen los números por colores o por letras para variar el desafío.",
  seguridad="Jueguen en una superficie plana y sin obstáculos para evitar caídas."),

 dict(n=21, slug="suelo-lava", tipo="recreativa",
  titulo="El suelo es lava",
  gancho="¡Cuidado! El piso es lava y solo los cojines te salvan de caer.",
  duracion="15-20 min", dp=2, dm=1,
  materiales=["Cojines, almohadas, hojas de diario o trozos de cartón","Un espacio amplio y despejado"],
  preparacion="Repartan los cojines por el suelo como islas seguras, separados entre sí.",
  pasos=["Declaren que el suelo es lava y solo los cojines son seguros.","Crucen la habitación saltando de cojín en cojín sin tocar el piso.","Si alguien pisa la «lava», vuelve al inicio entre risas.","Cambien las islas de lugar para crear recorridos nuevos.","Suban el desafío separando un poco más los cojines."],
  aprendizaje="Mejora el equilibrio, el salto y la planificación de movimientos. Imaginar un mundo de lava potencia el juego simbólico y la diversión en familia.",
  variantes="Agreguen reglas: cargar un peluche al cruzar o avanzar de espaldas.",
  seguridad="Asegura que los cojines no resbalen y despeja muebles con esquinas duras."),

 dict(n=22, slug="carrera-sacos", tipo="recreativa",
  titulo="Carrera de sacos",
  gancho="Meterse en un saco y avanzar a saltos: risas aseguradas para toda la familia.",
  duracion="15-20 min", dp=1, dm=1,
  materiales=["Una funda de almohada o un saco por participante","Un espacio amplio, mejor al aire libre"],
  preparacion="Marquen una línea de salida y una meta a pocos metros. Repartan los sacos.",
  pasos=["Cada uno se mete dentro de su saco y lo sujeta a la cintura.","Se ubican todos en la línea de salida.","A la cuenta de tres, avanzan dando saltitos hacia la meta.","El primero en cruzar gana, pero lo importante es divertirse.","Repitan la carrera o prueben en parejas tomados de la mano."],
  aprendizaje="Trabaja el equilibrio, la fuerza de las piernas y la coordinación al saltar. Competir con alegría enseña a ganar y perder con buen ánimo.",
  variantes="Hagan una carrera de relevos por equipos pasando el saco de uno a otro.",
  seguridad="Jueguen sobre pasto o una superficie blanda y acompañen a los más pequeños."),

 dict(n=23, slug="estatuas-musicales", tipo="recreativa",
  titulo="Estatuas musicales",
  gancho="Bailar mientras suena la música y quedarse congelado cuando para.",
  duracion="15 min", dp=1, dm=1,
  materiales=["Música alegre","Un aparato para pausarla","Espacio para moverse"],
  preparacion="Elige canciones movidas y despeja un espacio para bailar.",
  pasos=["Pon la música y bailen libremente por la sala.","Cuando pares la música de golpe, todos deben quedar como estatuas.","Quien se mueva, descansa un turno o hace una mueca divertida.","Vuelve a poner la música y a bailar.","Cambia el ritmo: bailar lento, rápido o como un animal."],
  aprendizaje="Desarrolla el control del cuerpo, la escucha activa y el autocontrol al detenerse. Bailar libera energía y mejora el ánimo de todos.",
  variantes="Den instrucciones al congelar: «estatua de cocodrilo» o «en un solo pie».",
  seguridad="Despeja el espacio de objetos y bailen descalzos o con calcetines antideslizantes."),

 dict(n=24, slug="memorice", tipo="juego",
  titulo="Memorice casero",
  gancho="Dar vuelta cartas y encontrar las parejas: un clásico para la memoria.",
  duracion="15-20 min", dp=2, dm=1,
  materiales=["Cartulina o cartón para las cartas","Plumones o stickers para los dibujos","Tijeras"],
  preparacion="Recorten pares de cartas iguales y dibujen o peguen una misma imagen en cada pareja.",
  pasos=["Mezclen las cartas y colóquenlas boca abajo en filas.","Por turnos, den vuelta dos cartas a la vista de todos.","Si son iguales, se las queda quien las encontró; si no, se vuelven a tapar.","Intenten recordar dónde estaba cada dibujo.","Gana quien reúna más parejas al terminar."],
  aprendizaje="Entrena la memoria visual, la atención y el respeto por los turnos. Recordar posiciones fortalece la concentración de forma divertida.",
  variantes="Hagan parejas de un dibujo con su palabra o con el número y su cantidad.",
  seguridad="Usen tijeras de punta redonda y un adulto ayuda con los recortes."),

 dict(n=25, slug="dado-acciones", tipo="juego",
  titulo="El dado de las acciones",
  gancho="Un dado gigante que manda saltar, girar o hacer el oso en cada tirada.",
  duracion="15 min", dp=2, dm=1,
  materiales=["Una caja cuadrada de cartón","Papel y plumones","Cinta"],
  preparacion="Forra la caja y dibuja una acción en cada cara: saltar, girar, aplaudir, agacharse, correr en el sitio, abrazar.",
  pasos=["Repasen juntos qué acción tiene cada cara del dado.","Por turnos, lancen el dado al aire o háganlo rodar.","Todos hacen la acción que salió, contando hasta diez.","Sigan turnándose para lanzar.","Inventen acciones nuevas y cámbienlas cuando se aburran."],
  aprendizaje="Combina movimiento, lenguaje y nociones de azar. Seguir instrucciones y esperar el turno desarrolla la atención y el autocontrol.",
  variantes="Hagan un dado de emociones: cada cara, una cara que imitar y nombrar.",
  seguridad="Jueguen en un espacio despejado, sobre todo si las acciones implican saltar."),

 dict(n=26, slug="pesca-magnetica", tipo="juego",
  titulo="Pesca magnética",
  gancho="Una caña con imán para pescar pececitos de papel: paciencia y puntería.",
  duracion="20 min", dp=2, dm=2,
  materiales=["Cartulina para los peces","Clips metálicos","Un palito o lápiz","Hilo","Un imán"],
  preparacion="Recorten pececitos, póngale un clip a cada uno y aten un imán al extremo de un hilo en el palito como caña.",
  pasos=["Esparzan los peces por el suelo o dentro de una caja-estanque.","Muéstrale cómo acercar el imán al clip para «pescar».","Que intente levantar un pez con la caña y soltarlo en un balde.","Cuenten cuántos peces lograron pescar.","Pongan números o colores en los peces para sumar un reto extra."],
  aprendizaje="Introduce el magnetismo de forma lúdica y afina la coordinación ojo-mano y la paciencia. Contar y clasificar los peces suma aprendizaje.",
  variantes="Pongan distintos puntajes a los peces y sumen al final quién pescó más.",
  seguridad="Vigila los clips y el imán, que son pequeños; un adulto los maneja con los más chicos."),

 dict(n=27, slug="bingo-dibujos", tipo="juego",
  titulo="Bingo de dibujos",
  gancho="Un bingo con dibujos en vez de números para jugar todos juntos.",
  duracion="20 min", dp=2, dm=1,
  materiales=["Cartones con cuadrículas de dibujos","Fichas o porotos para marcar","Tarjetas con los mismos dibujos para sacar"],
  preparacion="Dibujen cartones con seis imágenes cada uno y un mazo de tarjetas con todas las imágenes.",
  pasos=["Reparte un cartón y fichas a cada jugador.","Saca una tarjeta y nombra el dibujo en voz alta.","Quien lo tenga en su cartón, lo marca con una ficha.","Sigan sacando tarjetas hasta que alguien complete su cartón.","Quien lo llene grita «¡bingo!» y revisan juntos."],
  aprendizaje="Desarrolla la atención, el reconocimiento de imágenes y el vocabulario. Esperar el turno y escuchar fortalece habilidades sociales.",
  variantes="Cambien los dibujos por letras, colores o sonidos de animales que imitar.",
  seguridad="Usen fichas grandes que no sean riesgo para hermanos pequeños."),

 dict(n=28, slug="pintura-soplada", tipo="arte",
  titulo="Pintura soplada",
  gancho="Soplar gotas de pintura con una bombilla para crear ramas y monstruos locos.",
  duracion="20 min", dp=1, dm=2,
  materiales=["Témpera líquida o aguada","Una bombilla por persona","Papel grueso","Cucharas"],
  preparacion="Diluye la témpera con un poco de agua para que sea soplable y protege la mesa.",
  pasos=["Pon unas gotas de pintura líquida sobre el papel.","Muéstrale cómo soplar con la bombilla para esparcir la gota.","Que sople en distintas direcciones y vea aparecer ramas y formas.","Combinen colores y observen cómo se mezclan al chocar.","Cuando seque, busquen figuras escondidas en las manchas."],
  aprendizaje="Ejercita el soplo controlado, útil para el habla, y estimula la imaginación. Ver formas en las manchas desarrolla la creatividad y el lenguaje.",
  variantes="Agreguen ojos de papel a las manchas para convertirlas en criaturas divertidas.",
  seguridad="Recuerda soplar, nunca aspirar, por la bombilla; usa pinturas no tóxicas."),

 dict(n=29, slug="collage-geometrico", tipo="arte",
  titulo="Collage de figuras",
  gancho="Círculos, cuadrados y triángulos de colores para construir lo que imaginen.",
  duracion="20-30 min", dp=2, dm=1,
  materiales=["Papeles o cartulinas de colores","Tijeras de punta redonda","Pegamento","Una hoja base"],
  preparacion="Recorten muchas figuras geométricas de distintos tamaños y colores.",
  pasos=["Repasen juntos los nombres de las figuras: círculo, cuadrado, triángulo.","Que imagine qué quiere armar: una casa, un robot, un animal.","Vaya pegando las figuras sobre la hoja para formar su creación.","Conversen sobre los colores y las formas que va usando.","Cuelguen la obra terminada en un lugar visible."],
  aprendizaje="Refuerza el reconocimiento de figuras y colores y la motricidad fina al pegar. Componer una imagen con formas desarrolla la creatividad y la planificación.",
  variantes="Propongan un reto: armar algo usando solo triángulos, o un patrón que se repita.",
  seguridad="Usen tijeras de punta redonda y supervisen los recortes."),

 dict(n=30, slug="marioneta-calcetin", tipo="arte",
  titulo="Marioneta de calcetín",
  gancho="Un calcetín viejo se transforma en un personaje parlanchín con personalidad.",
  duracion="25-30 min", dp=1, dm=2,
  materiales=["Un calcetín limpio","Botones o trozos de fieltro para ojos","Lana para el pelo","Pegamento fuerte o aguja e hilo"],
  preparacion="Reúne los materiales y decide con el niño qué personaje crearán.",
  pasos=["Pónganse el calcetín en la mano para ver dónde va la boca.","Peguen o cosan los ojos sobre el empeine del calcetín.","Agreguen pelo de lana, orejas o lengua según el personaje.","Déjenlo secar si usaron pegamento.","Den vida a la marioneta con voz propia y monten una pequeña función."],
  aprendizaje="Fomenta la creatividad, el lenguaje y la expresión al inventar un personaje. Manipular la marioneta desarrolla la motricidad y la confianza para hablar.",
  variantes="Creen varias marionetas y armen una conversación o una historia entre ellas.",
  seguridad="Un adulto maneja la aguja si cosen; con los más pequeños, mejor pegar botones grandes."),

 dict(n=31, slug="mosaico-papel", tipo="arte",
  titulo="Mosaico de papel",
  gancho="Pegar trocitos de papel de colores para rellenar un dibujo como un mosaico.",
  duracion="25 min", dp=2, dm=1,
  materiales=["Papeles de colores o revistas","Pegamento en barra","Una hoja con un dibujo de contorno simple","Recipientes para clasificar"],
  preparacion="Rasguen o recorten muchos trocitos de papel y sepárenlos por color en recipientes. Dibuja un contorno simple para rellenar.",
  pasos=["Elijan un dibujo sencillo: una manzana, un pez, una estrella.","Pongan pegamento por zonas dentro del contorno.","Peguen los trocitos de papel rellenando cada zona con un color.","Vayan completando el dibujo como un mosaico de colores.","Dejen secar y muestren la obra terminada."],
  aprendizaje="Afina la pinza de los dedos y la paciencia al pegar trocitos pequeños. Clasificar por color y rellenar zonas desarrolla el orden y la concentración.",
  variantes="Hagan el mosaico con trozos de cáscara de huevo pintada o con legumbres.",
  seguridad="Vigila los trocitos pequeños con los hermanos menores."),

 dict(n=32, slug="termometro-emociones", tipo="emocional",
  titulo="El termómetro de las emociones",
  gancho="Una forma simpática de medir cómo nos sentimos y aprender a calmarnos.",
  duracion="20 min", dp=2, dm=1,
  materiales=["Cartulina","Plumones","Un palito o flecha de cartón con un broche"],
  preparacion="Dibuja un termómetro vertical con zonas de color: verde (tranquilo), amarillo (inquieto), rojo (muy enojado). Pon una flecha móvil.",
  pasos=["Conversen sobre cada zona y qué se siente en cada una.","Pídele que mueva la flecha para mostrar cómo se siente ahora.","Cuando esté en rojo, busquen juntos cómo bajar al verde.","Practiquen respirar hondo o abrazarse para calmarse.","Usen el termómetro otros días para hablar de emociones."],
  aprendizaje="Ayuda a reconocer y nombrar las emociones y a regularlas. Poner palabras a lo que se siente es la base de la inteligencia emocional.",
  variantes="Hagan un termómetro para cada miembro de la familia y compártanlo en la cena.",
  seguridad="Acepta todas las emociones sin juzgar; el objetivo es entenderlas, no esconderlas."),

 dict(n=33, slug="frasco-logros", tipo="emocional",
  titulo="El frasco de lo bueno",
  gancho="Un frasco que guarda los momentos lindos y los logros de cada día.",
  duracion="10 min al día", dp=1, dm=1,
  materiales=["Un frasco transparente","Papelitos de colores","Un lápiz"],
  preparacion="Decoren juntos el frasco y déjenlo en un lugar visible con papelitos al lado.",
  pasos=["Cada día, conversen sobre algo bueno que pasó o que el niño logró.","Escríbanlo (o dibújenlo) en un papelito.","Doblen el papel y métanlo en el frasco.","Vean cómo el frasco se va llenando de momentos felices.","Cada cierto tiempo, vacíenlo y lean juntos los recuerdos."],
  aprendizaje="Fomenta la gratitud, la autoestima y el hábito de fijarse en lo positivo. Recordar logros refuerza la confianza y el vínculo familiar.",
  variantes="Hagan un frasco de gratitud familiar donde todos aporten su momento del día.",
  seguridad="Valida cualquier logro, por pequeño que sea: lo importante es el reconocimiento."),

 dict(n=34, slug="cuento-peluches", tipo="emocional",
  titulo="Un cuento con peluches",
  gancho="Dar voz a los peluches para hablar de lo que sentimos jugando.",
  duracion="20 min", dp=1, dm=1,
  materiales=["Peluches o muñecos","Un espacio cómodo"],
  preparacion="Elijan un par de peluches y siéntense juntos en un lugar tranquilo.",
  pasos=["Inventen una historia simple donde un peluche siente algo: miedo, pena o alegría.","Hagan hablar a los peluches dándoles voz.","Pregunten al niño cómo podría ayudar el peluche a sentirse mejor.","Dejen que él dirija parte de la historia y proponga soluciones.","Cierren con un final cariñoso y un abrazo de los peluches."],
  aprendizaje="A través del juego simbólico, el niño explora y nombra emociones a distancia segura. Buscar soluciones para el peluche desarrolla la empatía.",
  variantes="Usen los peluches para ensayar situaciones reales, como el primer día de jardín.",
  seguridad="Sigue el ritmo del niño y no fuerces temas que no quiera tocar ese día."),

 dict(n=35, slug="poroto-algodon", tipo="naturaleza",
  titulo="Un poroto en algodón",
  gancho="Ver brotar y crecer una plantita día a día desde una semilla.",
  duracion="15 min + cuidado diario", dp=1, dm=1,
  materiales=["Un frasco o vaso transparente","Algodón","Un poroto o lenteja seca","Agua"],
  preparacion="Humedece el algodón y colócalo dentro del frasco.",
  pasos=["Pongan el poroto entre el algodón y el vidrio para poder verlo.","Mantengan el algodón siempre húmedo, sin encharcar.","Dejen el frasco en un lugar con luz.","Observen cada día y dibujen los cambios: la raíz, el tallo, las hojas.","Cuando crezca, trasplántenlo a una maceta con tierra."],
  aprendizaje="Muestra el ciclo de vida de una planta y enseña responsabilidad al cuidarla. Observar y registrar los cambios introduce la observación científica.",
  variantes="Siembren varios porotos y comparen cuál crece más según la luz o el agua.",
  seguridad="Recuerda que la semilla se siembra, no se come; lávense las manos al terminar."),

 dict(n=36, slug="comedero-pajaros", tipo="naturaleza",
  titulo="Comedero de pájaros",
  gancho="Invitar a los pájaros del barrio con un comedero hecho en casa.",
  duracion="20 min + observación", dp=2, dm=1,
  materiales=["Un tubo de cartón o una botella","Mantequilla de maní o margarina","Semillas o alpiste","Hilo para colgar"],
  preparacion="Reúne los materiales y elige un lugar tranquilo donde colgar el comedero, visible desde una ventana.",
  pasos=["Unten el tubo o la botella con una capa de mantequilla de maní.","Rueden el tubo sobre las semillas hasta que queden pegadas.","Pasen un hilo para poder colgarlo.","Cuélguenlo de una rama o reja a una altura segura.","Observen con paciencia qué pájaros llegan a comer y cuáles son."],
  aprendizaje="Conecta a los niños con la fauna cercana y fomenta el cuidado de los animales. Observar y reconocer pájaros desarrolla la atención y el respeto por la naturaleza.",
  variantes="Lleven un registro dibujado de los pájaros que visitan el comedero cada día.",
  seguridad="Cuelguen el comedero en un lugar seguro y lávense las manos después de manipular semillas."),
]

ORD = ["id","orden","edad","tipo","titulo","gancho","duracion","dif_prep","dif_materiales",
       "materiales","preparacion","pasos","aprendizaje","variantes","seguridad","imagen"]

def dump(d):
    return "\n".join(
        (yaml.safe_dump({k: d[k]}, allow_unicode=True, default_flow_style=False, sort_keys=False, width=100).rstrip())
        for k in ORD) + "\n"

for a in A:
    id_ = f"3a5-{a['n']:02d}"
    rec = dict(id=id_, orden=a["n"], edad="3-5", tipo=a["tipo"], titulo=a["titulo"],
               gancho=a["gancho"], duracion=a["duracion"], dif_prep=a["dp"], dif_materiales=a["dm"],
               materiales=a["materiales"], preparacion=a["preparacion"], pasos=a["pasos"],
               aprendizaje=a["aprendizaje"], variantes=a["variantes"], seguridad=a["seguridad"],
               imagen=f"{id_}.png")
    (DST / f"{id_}-{a['slug']}.yaml").write_text(dump(rec), encoding="utf-8")
    print("escrito", id_, a["titulo"])
print("Total:", len(A))
