#!/usr/bin/env python3
"""Crea las 24 actividades nuevas del rango 9-12 (ids 9a12-13 .. 9a12-36)."""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
DST = ROOT / "data" / "activities"

A = [
 dict(n=13, slug="robot-vibrador", tipo="experimento",
  titulo="Robot vibrador",
  gancho="Un motorcito, una pila y un vaso: tu primer robot que baila por la mesa.",
  duracion="30-40 min", dp=2, dm=3,
  materiales=["Un motor pequeño de juguete","Una pila AA con portapilas","Un vaso de plástico o un cepillo de dientes viejo","Plumones, cinta y un peso desigual para el eje","Plastilina"],
  preparacion="Reúne los materiales. Un adulto ayuda a identificar los cables del motor y del portapilas.",
  pasos=["Pega un trocito de plastilina en el eje del motor, descentrado, para que vibre.","Conecta los cables del motor a la pila y comprueba que gira.","Fija el motor y la pila sobre el vaso volcado con cinta.","Agrega plumones como patas o como lápices para que deje rastro.","Enciéndelo sobre una hoja y observen cómo se mueve y dibuja solo."],
  aprendizaje="Introduce circuitos eléctricos y la idea de que un peso descentrado produce vibración. Construir y ajustar el robot desarrolla el pensamiento de ingeniería.",
  variantes="Compitan a ver qué robot dibuja el recorrido más loco o se mueve más rápido.",
  seguridad="Un adulto supervisa las conexiones; no usar enchufes ni pilas dañadas."),

 dict(n=14, slug="circuito-electrico", tipo="experimento",
  titulo="Mi primer circuito",
  gancho="Encender una ampolleta con una pila y un par de cables: la chispa de la electrónica.",
  duracion="30 min", dp=2, dm=2,
  materiales=["Una pila","Una ampolleta pequeña (LED o de linterna)","Cables o papel aluminio","Cinta","Un interruptor casero con un clip (opcional)"],
  preparacion="Reúne los materiales sobre la mesa. Un adulto revisa que la ampolleta sea de bajo voltaje.",
  pasos=["Conecten un cable de un polo de la pila a la ampolleta.","Conecten otro cable del otro polo para cerrar el circuito.","Observen cómo la ampolleta se enciende al cerrar el camino.","Agreguen un clip como interruptor para encender y apagar.","Prueben qué materiales dejan pasar la corriente y cuáles no."],
  aprendizaje="Demuestra que la electricidad necesita un circuito cerrado para fluir. Probar conductores y aislantes enseña a investigar de forma ordenada.",
  variantes="Hagan un juego de «pulso firme»: un cable con aro que no debe tocar otro sin encender la luz.",
  seguridad="Usen solo pilas y ampolletas de bajo voltaje, nunca la corriente del enchufe."),

 dict(n=15, slug="cohete-botella", tipo="experimento",
  titulo="Cohete de agua y aire",
  gancho="Bombear aire en una botella con agua y… ¡despegue al cielo!",
  duracion="30 min", dp=3, dm=2,
  materiales=["Una botella de plástico","Un corcho que selle la boca","Una bomba de inflar con aguja","Agua","Un soporte de lanzamiento al aire libre"],
  preparacion="Un adulto prepara el corcho con la aguja de la bomba atravesada. Realicen la actividad en un espacio abierto.",
  pasos=["Llenen un tercio de la botella con agua.","Sellen la boca con el corcho y la aguja de la bomba.","Pongan la botella boca abajo en el soporte, lejos de personas.","Bombeen aire y observen cómo la presión sube.","Aléjense y vean cómo el cohete despega cuando salta el corcho."],
  aprendizaje="Muestra la acción y reacción: el agua sale hacia abajo y empuja el cohete hacia arriba. Medir agua y presión convierte el juego en un experimento real.",
  variantes="Prueben distintas cantidades de agua y midan cuál logra el lanzamiento más alto.",
  seguridad="Solo al aire libre y lejos de personas; un adulto dirige el lanzamiento y nadie se asoma sobre el cohete."),

 dict(n=16, slug="torre-densidad", tipo="experimento",
  titulo="Torre de líquidos",
  gancho="Apilar líquidos en capas de colores que no se mezclan, como un arcoíris en un vaso.",
  duracion="30 min", dp=2, dm=2,
  materiales=["Un vaso alto y transparente","Miel","Lavalozas","Agua con colorante","Aceite","Alcohol con colorante","Una cuchara"],
  preparacion="Reúne los líquidos en el orden de densidad, de más pesado a más liviano.",
  pasos=["Viertan primero la miel en el fondo, al centro del vaso.","Agreguen con cuidado el lavalozas, luego el agua de color.","Echen el aceite y por último el alcohol de color, muy despacio.","Dejen resbalar cada líquido por la cuchara para no mezclarlos.","Observen las capas y predigan dónde quedará un objeto que dejen caer."],
  aprendizaje="Demuestra que los líquidos tienen distinta densidad y se ordenan por su peso. Verter con cuidado y predecir resultados afina la observación científica.",
  variantes="Dejen caer objetos pequeños y vean en qué capa quedan flotando según su densidad.",
  seguridad="El alcohol lo maneja un adulto; ningún líquido se bebe."),

 dict(n=17, slug="tinta-invisible", tipo="experimento",
  titulo="Tinta invisible",
  gancho="Escribir mensajes secretos que solo aparecen con el calor.",
  duracion="25 min", dp=1, dm=1,
  materiales=["Jugo de limón","Un pincel, hisopo o palillo","Papel blanco","Una fuente de calor (lámpara o plancha, manejada por un adulto)"],
  preparacion="Exprime el limón en un recipiente y reparte hisopos o pinceles finos.",
  pasos=["Mojen el pincel en jugo de limón y escriban un mensaje en el papel.","Dejen secar hasta que el mensaje sea invisible.","Intercambien los papeles con otra persona.","Con ayuda de un adulto, acerquen el papel a una fuente de calor.","Observen cómo el mensaje aparece dorado por el calor."],
  aprendizaje="Muestra una reacción química: el jugo se oscurece antes que el papel al calentarse. Escribir y revelar mensajes une ciencia, lenguaje y juego.",
  variantes="Prueben con otros «tintas» como leche o jugo de cebolla y comparen los resultados.",
  seguridad="La fuente de calor la maneja siempre un adulto para evitar quemaduras."),

 dict(n=18, slug="puente-papel", tipo="experimento",
  titulo="Desafío del puente de papel",
  gancho="¿Cuánto peso aguanta un puente de papel? Diseña, prueba y mejora.",
  duracion="40 min", dp=1, dm=1,
  materiales=["Hojas de papel","Dos libros o cajas como apoyos","Monedas o pesos pequeños para probar","Cinta (opcional)"],
  preparacion="Coloquen dos libros separados como pilares y dejen el papel y los pesos a mano.",
  pasos=["Apoyen una hoja plana entre los dos libros como primer puente.","Pongan monedas encima y cuenten cuántas aguanta antes de caer.","Modifiquen el papel: dóblenlo en acordeón, hagan un tubo o vigas.","Prueben cada diseño con el mismo método y anoten los resultados.","Comparen qué forma resistió más peso y conversen por qué."],
  aprendizaje="Introduce la ingeniería estructural: la forma del material cambia su resistencia. Diseñar, probar y mejorar es el corazón del método científico.",
  variantes="Hagan un concurso por equipos con la misma cantidad de papel y cinta.",
  seguridad="Actividad muy segura; cuiden solo de no dejar caer pesos sobre los pies."),

 dict(n=19, slug="catapulta-palitos", tipo="recreativa",
  titulo="Catapulta de palitos",
  gancho="Una catapulta casera para lanzar pompones lo más lejos posible.",
  duracion="30 min", dp=2, dm=2,
  materiales=["Palitos de helado","Gomas elásticas","Una tapa de botella o cuchara pequeña","Pompones o bolitas de papel"],
  preparacion="Reúne los palitos y las gomas. Decidan juntos el diseño básico de la catapulta.",
  pasos=["Apilen varios palitos y átenlos con gomas en los extremos.","Crucen dos palitos en forma de palanca y únanlos con goma.","Peguen una tapa al extremo del brazo como cuchara.","Coloquen un pompón y presionen el brazo para lanzarlo.","Midan los lanzamientos y ajusten la catapulta para llegar más lejos."],
  aprendizaje="Demuestra cómo una palanca almacena y libera energía para lanzar. Ajustar el diseño para mejorar el alcance desarrolla la lógica y la perseverancia.",
  variantes="Marquen una diana con puntajes y compitan por puntería en vez de distancia.",
  seguridad="Lancen solo objetos blandos y nunca apunten a las personas ni a la cara."),

 dict(n=20, slug="carrera-orientacion", tipo="recreativa",
  titulo="Carrera de orientación",
  gancho="Pistas y un mapa casero para encontrar puntos escondidos por la casa o el patio.",
  duracion="30-40 min", dp=2, dm=1,
  materiales=["Papel para dibujar un mapa","Tarjetas con pistas o números","Lápices","Un cronómetro (opcional)"],
  preparacion="Un adulto o un equipo dibuja un mapa simple del lugar y esconde tarjetas numeradas en distintos puntos.",
  pasos=["Entreguen el mapa con los puntos a encontrar marcados.","Cada equipo busca las tarjetas en el orden que indique el mapa.","En cada punto, anoten la palabra o el código de la tarjeta.","Sigan el recorrido hasta reunir todas las pistas.","Gana quien complete el circuito o resuelva el mensaje final."],
  aprendizaje="Desarrolla la orientación espacial, la lectura de mapas y el trabajo en equipo. Planear la ruta y resolver pistas entrena la lógica y la cooperación.",
  variantes="Sumen una brújula real o desafíos físicos en cada punto del recorrido.",
  seguridad="Definan bien los límites del juego para que nadie se aleje de zonas seguras."),

 dict(n=21, slug="comba-rutina", tipo="recreativa",
  titulo="Desafíos con la cuerda",
  gancho="Saltar la cuerda con rutinas y canciones para superar tus propias marcas.",
  duracion="20-30 min", dp=1, dm=1,
  materiales=["Una cuerda para saltar","Espacio amplio y despejado","Música o canciones de salto (opcional)"],
  preparacion="Busquen un espacio plano y sin obstáculos. Ajusten el largo de la cuerda a la estatura.",
  pasos=["Calienten con saltos suaves sin cuerda.","Practiquen el salto básico hasta encadenar varios seguidos.","Cuenten cuántos saltos logran sin parar y anoten su marca.","Sumen desafíos: salto cruzado, a un pie o a dúo.","Inventen rutinas con canciones y compitan de forma amistosa."],
  aprendizaje="Mejora la coordinación, el ritmo y la resistencia cardiovascular. Superar marcas propias enseña constancia y autosuperación.",
  variantes="Hagan saltos en grupo con una cuerda larga y dos personas girándola.",
  seguridad="Salten sobre una superficie plana y con calzado adecuado para cuidar las articulaciones."),

 dict(n=22, slug="stop-categorias", tipo="juego",
  titulo="Stop de categorías",
  gancho="Una letra y a llenar categorías a toda velocidad: nombre, animal, color, país…",
  duracion="20-30 min", dp=1, dm=1,
  materiales=["Hojas y lápices para cada jugador","Una tabla con categorías"],
  preparacion="Dibujen en cada hoja una tabla con columnas: nombre, animal, comida, color, país, objeto, y una para la puntuación.",
  pasos=["Alguien dice el abecedario en voz baja y otro lo detiene con un «¡stop!».","La letra donde se detuvo es la de la ronda.","Todos escriben una palabra de esa letra en cada categoría.","El primero en completar grita «¡stop!» y todos dejan de escribir.","Comparen respuestas y sumen puntos según las reglas acordadas."],
  aprendizaje="Amplía el vocabulario y la agilidad mental al buscar palabras por categorías. Pensar rápido y bajo presión entrena la memoria y la flexibilidad.",
  variantes="Cambien las categorías por temas: ciencia, deportes, películas o palabras en inglés.",
  seguridad="Acuerden las reglas de puntaje antes de empezar para evitar discusiones."),

 dict(n=23, slug="adivina-personaje", tipo="juego",
  titulo="¿Quién soy?",
  gancho="Un personaje pegado en la frente y preguntas de sí o no para adivinarlo.",
  duracion="20 min", dp=1, dm=1,
  materiales=["Papelitos o tarjetas","Lápices","Cinta o una vincha para sujetar la tarjeta"],
  preparacion="Cada uno escribe en una tarjeta un personaje conocido sin que los demás lo vean.",
  pasos=["Péguense una tarjeta en la frente sin mirarla.","Por turnos, hagan preguntas de sí o no: «¿soy real?», «¿soy un animal?».","Usen las respuestas para ir descartando posibilidades.","Quien crea saberlo, arriesga una respuesta en su turno.","Gana quien adivine su personaje con menos preguntas."],
  aprendizaje="Estimula el razonamiento deductivo y la formulación de buenas preguntas. Descartar opciones de forma lógica es una habilidad clave del pensamiento.",
  variantes="Limiten las categorías a animales, deportistas o personajes de cuentos.",
  seguridad="Elijan personajes conocidos por todos para que el juego sea justo y divertido."),

 dict(n=24, slug="ajedrez-damas", tipo="juego",
  titulo="Tablero de damas casero",
  gancho="Un tablero hecho a mano para aprender a planear jugadas y anticipar al rival.",
  duracion="30 min + partidas", dp=2, dm=1,
  materiales=["Cartón o cartulina para el tablero","Plumones o pintura","Tapas o cartones de dos colores como fichas"],
  preparacion="Dibujen un tablero de ocho por ocho casillas alternando dos colores. Preparen doce fichas de cada color.",
  pasos=["Coloquen las fichas en las tres primeras filas de cada lado, en las casillas oscuras.","Muevan en diagonal hacia adelante, de a una casilla.","Coman las fichas del rival saltando por encima cuando se pueda.","Cuando una ficha llega al fondo, se corona y puede ir en ambos sentidos.","Gana quien capture todas las fichas del rival o lo deje sin movimientos."],
  aprendizaje="Desarrolla la estrategia, la anticipación y la paciencia para planear varias jugadas. Construir su propio tablero suma valor al aprendizaje.",
  variantes="Una vez dominado, usen el mismo tablero para aprender los movimientos del ajedrez.",
  seguridad="Actividad tranquila; cuiden solo de usar fichas seguras si hay niños pequeños."),

 dict(n=25, slug="sudoku-logica", tipo="juego",
  titulo="Retos de lógica",
  gancho="Sudokus y acertijos para entrenar la mente como un gimnasio del cerebro.",
  duracion="20-30 min", dp=1, dm=1,
  materiales=["Sudokus sencillos impresos o dibujados","Acertijos y laberintos","Lápiz y goma"],
  preparacion="Preparen o impriman sudokus fáciles (4x4 o 6x6 para empezar) y un par de acertijos.",
  pasos=["Expliquen la regla del sudoku: no repetir números en fila, columna ni región.","Empiecen por las casillas más fáciles de deducir.","Usen lápiz para poder corregir sin frustrarse.","Cuando se atasquen, busquen otra fila o columna para avanzar.","Al terminar, prueben un acertijo o laberinto como premio."],
  aprendizaje="Entrena el razonamiento lógico, la concentración y la perseverancia. Deducir paso a paso y corregir errores fortalece el pensamiento estructurado.",
  variantes="Suban poco a poco la dificultad o inventen sus propios acertijos para la familia.",
  seguridad="Si la frustración aparece, hagan una pausa: el objetivo es disfrutar el reto."),

 dict(n=26, slug="stop-motion", tipo="arte",
  titulo="Película en stop motion",
  gancho="Mover figuras foto a foto para crear tu propia película animada.",
  duracion="45-60 min", dp=2, dm=2,
  materiales=["Un celular o tablet con cámara","Una app de stop motion gratuita","Juguetes, plastilina o recortes","Un soporte para apoyar la cámara fija"],
  preparacion="Con ayuda, instalen una app sencilla de stop motion y elijan los personajes y un fondo.",
  pasos=["Apoyen la cámara fija para que no se mueva entre fotos.","Coloquen los personajes en su posición inicial y tomen una foto.","Muevan un poquito los personajes y tomen otra foto.","Repitan moviendo de a poco para crear el movimiento.","Reproduzcan la secuencia y agreguen sonido o música."],
  aprendizaje="Combina arte, narración y tecnología, y enseña que el cine es ilusión de movimiento. Planear una historia cuadro a cuadro desarrolla la paciencia y la creatividad.",
  variantes="Hagan que un objeto aparezca o desaparezca, o que la plastilina se transforme.",
  seguridad="Acuerden tiempos de pantalla y supervisen el uso del dispositivo."),

 dict(n=27, slug="mandalas", tipo="arte",
  titulo="Mandalas para relajarse",
  gancho="Dibujar patrones que se repiten desde el centro para concentrarse y calmar la mente.",
  duracion="30 min", dp=1, dm=1,
  materiales=["Papel","Un compás o un vaso para trazar círculos","Lápices, plumones o colores","Regla"],
  preparacion="Tracen uno o dos círculos concéntricos como base del mandala.",
  pasos=["Marquen un punto central y divídanlo en partes iguales como una torta.","Dibujen una figura simple en el centro.","Repitan el mismo patrón en cada sección hacia afuera.","Vayan sumando anillos de formas que se repiten.","Coloreen con calma combinando los colores que más les gusten."],
  aprendizaje="Fomenta la concentración, la simetría y la calma a través del dibujo repetitivo. Crear patrones une arte, geometría y relajación.",
  variantes="Hagan mandalas con elementos naturales en el suelo o con puntos de colores.",
  seguridad="Actividad tranquila y segura, ideal para momentos de calma."),

 dict(n=28, slug="teatro-sombras", tipo="arte",
  titulo="Teatro de sombras",
  gancho="Siluetas de cartón y una linterna para montar una función de sombras chinescas.",
  duracion="40 min", dp=2, dm=2,
  materiales=["Cartón para las siluetas","Palitos para sostenerlas","Una sábana blanca o una pared clara","Una linterna o lámpara","Tijeras"],
  preparacion="Cuelguen una sábana y ubiquen la linterna detrás. Decidan una historia y sus personajes.",
  pasos=["Recorten en cartón las siluetas de los personajes.","Peguen un palito a cada silueta para manejarla.","Apaguen la luz y enciendan la linterna detrás de la sábana.","Muevan las siluetas entre la luz y la tela para proyectar sombras.","Representen la historia poniendo voces a cada personaje."],
  aprendizaje="Une arte, ciencia de la luz y expresión teatral en un solo proyecto. Inventar y representar una historia desarrolla el lenguaje y la creatividad.",
  variantes="Acerquen o alejen las siluetas de la luz para ver cómo crecen y encogen las sombras.",
  seguridad="Un adulto ayuda con los recortes y con el manejo de la lámpara para evitar el calor."),

 dict(n=29, slug="tie-dye", tipo="arte",
  titulo="Teñido de polera",
  gancho="Anudar, teñir y descubrir un diseño único e irrepetible en tu propia ropa.",
  duracion="40 min + secado", dp=2, dm=2,
  materiales=["Una polera o tela blanca de algodón","Tintura para ropa o témpera diluida","Gomas elásticas","Guantes","Un recipiente y plástico para proteger"],
  preparacion="Protejan bien la mesa y pónganse guantes. Preparen los colores en recipientes.",
  pasos=["Anuden la tela con gomas en espiral, nudos o pliegues.","Apliquen los colores sobre las distintas zonas anudadas.","Dejen reposar el tiempo que indique la tintura.","Enjuaguen, quiten las gomas y descubran el diseño.","Dejen secar y planchen con ayuda para fijar el color."],
  aprendizaje="Explora la mezcla de colores y cómo los pliegues crean patrones inesperados. Diseñar algo propio fomenta la creatividad y la identidad.",
  variantes="Prueben distintas técnicas de anudado y comparen los patrones que resultan.",
  seguridad="Usen guantes y un adulto maneja la tintura y la plancha."),

 dict(n=30, slug="carta-yo-futuro", tipo="emocional",
  titulo="Carta a mi yo del futuro",
  gancho="Escribir una carta para abrir dentro de un año y conversar con tu yo de hoy.",
  duracion="30 min", dp=1, dm=1,
  materiales=["Papel y lápiz","Un sobre","Stickers o decoración (opcional)"],
  preparacion="Busquen un momento tranquilo para pensar y escribir sin apuro.",
  pasos=["Piensen cómo son hoy: lo que les gusta, sus amigos, sus sueños.","Escriban una carta dirigida a sí mismos dentro de un año.","Incluyan metas, preguntas y un mensaje de ánimo.","Guarden la carta en un sobre cerrado con la fecha de apertura.","Anoten en el calendario cuándo abrirla y guárdenla en un lugar seguro."],
  aprendizaje="Favorece el autoconocimiento y la reflexión sobre los propios cambios y metas. Mirarse en el tiempo desarrolla la identidad y el sentido de progreso.",
  variantes="Hagan una versión familiar y ábranlas todos juntos en una fecha especial.",
  seguridad="Es un espacio íntimo: respeten que la carta es personal y privada."),

 dict(n=31, slug="tablero-metas", tipo="emocional",
  titulo="Tablero de sueños",
  gancho="Un collage de imágenes y palabras que reúne tus metas y lo que te inspira.",
  duracion="40 min", dp=1, dm=1,
  materiales=["Una cartulina grande","Revistas, fotos o dibujos","Tijeras y pegamento","Plumones"],
  preparacion="Reúnan revistas y materiales para recortar y conversen sobre sueños y metas.",
  pasos=["Piensen en metas para distintas áreas: aprender, crear, ayudar, disfrutar.","Busquen o dibujen imágenes y palabras que las representen.","Recórtenlas y organícenlas sobre la cartulina.","Péguenlas formando un collage que les inspire.","Cuelguen el tablero en un lugar visible y revísenlo cada cierto tiempo."],
  aprendizaje="Ayuda a imaginar el futuro y a poner en palabras los propios deseos y metas. Visualizar objetivos fomenta la motivación y la autoestima.",
  variantes="Actualicen el tablero al cumplir metas o al descubrir nuevos intereses.",
  seguridad="Recuerden que las metas son personales: no se comparan ni se compiten."),

 dict(n=32, slug="diario-emociones", tipo="emocional",
  titulo="Bitácora de emociones",
  gancho="Un cuaderno para registrar cómo te sientes y entender mejor lo que te pasa.",
  duracion="10-15 min al día", dp=1, dm=1,
  materiales=["Un cuaderno","Lápices de colores","Una escala o lista de emociones de referencia"],
  preparacion="Decoren la libreta y acuerden un momento del día para escribir, sin presiones.",
  pasos=["Cada día, identifiquen la emoción principal que sintieron.","Anoten qué la provocó y cómo reaccionaron.","Dibujen o pongan color a esa emoción si quieren.","Reflexionen sobre qué les ayudaría la próxima vez.","Cada cierto tiempo, lean atrás y busquen patrones."],
  aprendizaje="Desarrolla la inteligencia emocional al nombrar, registrar y comprender lo que se siente. Escribir sobre las emociones ayuda a regularlas y a conocerse mejor.",
  variantes="Agreguen una sección de gratitud o de logros del día.",
  seguridad="Es un espacio privado y libre de juicio; acompañen sin obligar a compartir."),

 dict(n=33, slug="compostera", tipo="naturaleza",
  titulo="Compostera casera",
  gancho="Convertir restos de comida en abono y descubrir cómo la naturaleza recicla.",
  duracion="30 min + semanas de cuidado", dp=2, dm=1,
  materiales=["Un balde o caja con tapa","Restos de frutas y verduras","Hojas secas, papel o cartón","Un poco de tierra","Una herramienta para remover"],
  preparacion="Un adulto ayuda a hacer agujeros en el balde para que entre aire. Elijan un lugar al aire libre.",
  pasos=["Pongan una capa de tierra y hojas secas en el fondo.","Agreguen restos de frutas y verduras picados.","Cubran con más hojas secas o papel para equilibrar la humedad.","Remuevan cada pocos días para airear la mezcla.","Observen durante semanas cómo se transforma en abono oscuro."],
  aprendizaje="Enseña el ciclo de la materia y el papel de los descomponedores en la naturaleza. Cuidar la compostera fomenta la responsabilidad ambiental.",
  variantes="Comparen qué restos se descomponen más rápido o críen lombrices para acelerar el proceso.",
  seguridad="No incluyan carnes ni lácteos y lávense las manos después de manipular la compostera."),

 dict(n=34, slug="observar-estrellas", tipo="naturaleza",
  titulo="Observadores de estrellas",
  gancho="Un mapa del cielo y una noche despejada para encontrar constelaciones.",
  duracion="40 min", dp=2, dm=1,
  materiales=["Un mapa celeste o una app de astronomía","Una linterna con papel rojo","Una manta para tenderse","Abrigo"],
  preparacion="Elijan una noche despejada y un lugar oscuro, lejos de luces. Cubran la linterna con papel rojo para no encandilarse.",
  pasos=["Tiéndanse de espaldas y dejen que la vista se acostumbre a la oscuridad.","Ubiquen una estrella o constelación brillante de referencia.","Usen el mapa o la app para identificar constelaciones.","Sigan el recorrido buscando otras figuras en el cielo.","Anoten o dibujen lo que encontraron y conversen sobre el universo."],
  aprendizaje="Despierta la curiosidad por la astronomía y la orientación con las estrellas. Observar el cielo conecta ciencia, paciencia y asombro por el universo.",
  variantes="Investiguen los mitos detrás de las constelaciones o busquen planetas visibles.",
  seguridad="Vayan acompañados de un adulto y abríguense bien para la noche al aire libre."),

 dict(n=35, slug="filtro-agua", tipo="naturaleza",
  titulo="Filtro de agua casero",
  gancho="Construir un filtro con piedras y arena para ver cómo se limpia el agua sucia.",
  duracion="40 min", dp=2, dm=2,
  materiales=["Una botella de plástico cortada","Piedras, arena y carbón vegetal","Algodón o un paño","Agua con tierra para filtrar","Un vaso para recoger"],
  preparacion="Un adulto corta la botella por la mitad para usarla invertida como embudo.",
  pasos=["Pongan el algodón en el cuello de la botella invertida.","Agreguen capas de carbón, arena fina y piedras, de fina a gruesa.","Preparen agua sucia mezclando tierra con agua limpia.","Viertan el agua sucia por arriba y recójanla abajo.","Comparen el agua antes y después de pasar por el filtro."],
  aprendizaje="Muestra cómo distintas capas atrapan las impurezas y de dónde viene el agua potable. Construir y probar el filtro enseña ciencia y cuidado del agua.",
  variantes="Prueben distintos órdenes de capas y comparen cuál limpia mejor.",
  seguridad="El agua filtrada NO se bebe; el experimento es solo para observar la limpieza física."),

 dict(n=36, slug="bitacora-aves", tipo="naturaleza",
  titulo="Bitácora de aves",
  gancho="Salir a observar pájaros y registrar cada especie como un naturalista.",
  duracion="40 min + observaciones", dp=1, dm=1,
  materiales=["Una libreta y lápices","Binoculares (opcional)","Una guía de aves de la zona o una app"],
  preparacion="Elijan un lugar con árboles y un horario tranquilo, mejor temprano en la mañana.",
  pasos=["Caminen en silencio y observen los árboles y el cielo.","Cuando vean un ave, fíjense en su tamaño, color y canto.","Dibújenla y anoten dónde y cuándo la vieron.","Búsquenla en la guía o la app para identificar la especie.","Vuelvan otros días y vayan completando su bitácora."],
  aprendizaje="Desarrolla la observación, la paciencia y el conocimiento de la fauna local. Registrar y clasificar especies introduce el trabajo del naturalista.",
  variantes="Lleven un conteo de cuántas especies distintas logran observar en un mes.",
  seguridad="Observen sin molestar a los animales y vayan acompañados a lugares abiertos."),
]

ORD = ["id","orden","edad","tipo","titulo","gancho","duracion","dif_prep","dif_materiales",
       "materiales","preparacion","pasos","aprendizaje","variantes","seguridad","imagen"]

def dump(d):
    return "\n".join(
        (yaml.safe_dump({k: d[k]}, allow_unicode=True, default_flow_style=False, sort_keys=False, width=100).rstrip())
        for k in ORD) + "\n"

for a in A:
    id_ = f"9a12-{a['n']:02d}"
    rec = dict(id=id_, orden=a["n"], edad="9-12", tipo=a["tipo"], titulo=a["titulo"],
               gancho=a["gancho"], duracion=a["duracion"], dif_prep=a["dp"], dif_materiales=a["dm"],
               materiales=a["materiales"], preparacion=a["preparacion"], pasos=a["pasos"],
               aprendizaje=a["aprendizaje"], variantes=a["variantes"], seguridad=a["seguridad"],
               imagen=f"{id_}.png")
    (DST / f"{id_}-{a['slug']}.yaml").write_text(dump(rec), encoding="utf-8")
    print("escrito", id_, a["titulo"])
print("Total:", len(A))
