#!/usr/bin/env python3
"""Crea las 24 actividades nuevas del rango 0-2 (ids 0a2-13 .. 0a2-36)."""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
DST = ROOT / "data" / "activities"

A = [
 dict(n=13, slug="bolsa-sensorial", tipo="sensorial",
  titulo="Bolsa sensorial sin manchas",
  gancho="Pintar y apretar colores con los dedos… sin ensuciarse ni una mano.",
  duracion="10-15 min", dp=1, dm=1,
  materiales=["Una bolsa de congelar con cierre hermético","Pintura de dedos, gel de baño con colorante o crema","Cinta adhesiva fuerte"],
  preparacion="Pon dos o tres cucharadas de pintura o gel de colores dentro de la bolsa, saca el aire y ciérrala. Refuerza el cierre con cinta y pégala sobre una mesa o el suelo.",
  pasos=["Sienta al bebé frente a la bolsa pegada a la superficie.","Apoya tú primero un dedo y presiona para mostrarle cómo se mueve el color.","Deja que aplaste, arrastre y mezcle los colores apretando la bolsa.","Nombra los colores y lo que ocurre: «mira cómo se junta el azul con el amarillo».","Cuando se canse, despega la bolsa y guárdala para otro día."],
  aprendizaje="Estimula el tacto y la vista sin riesgo de que se lleve la pintura a la boca. Apretar y arrastrar fortalece los músculos de las manos, base de la futura escritura.",
  variantes="Mete dentro purpurina, una hoja o un botón grande para que los empuje por la bolsa.",
  seguridad="Sella muy bien el cierre con cinta y no dejes nunca la bolsa al alcance sin supervisión."),

 dict(n=14, slug="camino-texturas-pies", tipo="sensorial",
  titulo="Camino de texturas para los pies",
  gancho="Un recorrido para caminar descalzo y sentir el mundo con la planta de los pies.",
  duracion="15 min", dp=2, dm=1,
  materiales=["Superficies de distintas texturas (toalla, alfombra, papel de burbujas, esponja, fieltro)","Cinta adhesiva para fijarlas al suelo"],
  preparacion="Coloca las distintas texturas en fila sobre el suelo y fíjalas con cinta para que no resbalen. Procura una zona despejada y segura.",
  pasos=["Descalza al bebé y tómalo de las manos para darle seguridad.","Ayúdalo a pisar la primera textura y observa su reacción.","Avanza despacio de una superficie a otra, nombrando lo que siente.","Si aún no camina, siéntalo y guía sus pies y manos sobre cada textura.","Repitan el camino tantas veces como quiera, en los dos sentidos."],
  aprendizaje="Despierta la sensibilidad de los pies y mejora el equilibrio y la conciencia del cuerpo. Asociar sensaciones con palabras enriquece su vocabulario.",
  variantes="Termina el camino con un cojín mullido donde dejarse caer, o hazlo en el jardín con pasto y arena.",
  seguridad="Acompáñalo siempre tomado de la mano y revisa que las texturas no resbalen ni tengan bordes ásperos."),

 dict(n=15, slug="hielo-colores", tipo="sensorial",
  titulo="Cubos de hielo de colores",
  gancho="Frío, brillante y de colores: el hielo es pura magia sensorial.",
  duracion="10-15 min", dp=2, dm=1,
  materiales=["Cubeta de hielo","Agua con unas gotas de colorante de alimentos","Una bandeja con borde","Una toalla"],
  preparacion="La noche anterior, congela agua con colorante en la cubetera. Antes de empezar, prepara la bandeja sobre una toalla en un lugar fácil de limpiar.",
  pasos=["Pon uno o dos cubos de hielo de colores en la bandeja.","Toca tú un cubo y di «¡qué frío!» para mostrarle la sensación.","Deja que el bebé los toque, empuje y vea cómo resbalan y se derriten.","Nombra los colores y observa cómo el hielo deja un rastro de color al moverse.","Cuando termine, sécale bien las manos para que entre en calor."],
  aprendizaje="Introduce las nociones de frío, derretir y color a través de la experiencia directa. El asombro ante el cambio del hielo alimenta la curiosidad científica temprana.",
  variantes="Congela un juguetito pequeño dentro del hielo y descubran juntos cómo aparece al derretirse (con supervisión).",
  seguridad="Ofrece el hielo por ratos cortos para no enfriar demasiado las manos y vigila que no lo lleve a la boca."),

 dict(n=16, slug="tarjetas-contraste", tipo="sensorial",
  titulo="Tarjetas de alto contraste",
  gancho="Para los más pequeñitos: dibujos en blanco y negro que atrapan su mirada.",
  duracion="5-10 min", dp=2, dm=1,
  materiales=["Cartulinas blancas","Plumón negro grueso","Plástico para forrar o fundas (opcional)"],
  preparacion="Dibuja figuras simples y grandes en negro sobre fondo blanco: espirales, rayas, círculos, una cara sencilla. Una figura por tarjeta.",
  pasos=["Recuesta al bebé boca arriba o sostenlo en tus brazos.","Acerca una tarjeta a unos 25-30 cm de su cara.","Muévela muy despacio de un lado a otro y observa cómo la sigue con la mirada.","Cambia de tarjeta cuando notes que pierde interés.","Habla con él suavemente mientras mira: «¿ves las rayas?»."],
  aprendizaje="Estimula la visión, que en los primeros meses distingue mejor los fuertes contrastes. Seguir la tarjeta con los ojos ejercita el control de la mirada y la atención.",
  variantes="A medida que crece, usa tarjetas con dos colores muy contrastados o con caras de distintas emociones.",
  seguridad="No fuerces su atención: si gira la cara o se inquieta, está pidiendo un descanso."),

 dict(n=17, slug="globos-sensoriales", tipo="sensorial",
  titulo="Globos para apretar",
  gancho="Globos rellenos de distintos materiales para amasar y descubrir con las manos.",
  duracion="10 min", dp=2, dm=1,
  materiales=["Globos resistentes","Rellenos variados (harina, arroz, lentejas, un poco de agua)","Un embudo o una botella cortada"],
  preparacion="Rellena cada globo con un material distinto usando el embudo y haz un buen nudo. Pasa cinta sobre el nudo para reforzarlo. Prepara tres o cuatro globos.",
  pasos=["Ofrece al bebé un globo y deja que lo tome y lo apriete.","Guía sus manos para que sienta lo blando, lo duro o lo que cruje.","Ve cambiando de globo y nombra las sensaciones.","Aprieta tú uno y deja que vea cómo cambia de forma.","Junta todos en una canasta para que elija el que más le guste."],
  aprendizaje="Fortalece la musculatura de las manos y afina el tacto al comparar texturas y pesos. Manipular distintos rellenos desarrolla la coordinación y la concentración.",
  variantes="Haz dos globos iguales y juega a que encuentre la pareja por el tacto.",
  seguridad="Supervisión constante: los globos son peligro de asfixia. Refuerza muy bien los nudos y retíralos si se ven dañados."),

 dict(n=18, slug="persecucion-pelota", tipo="recreativa",
  titulo="Atrapa la pelota",
  gancho="Una pelota que rueda es una invitación irresistible a gatear y moverse.",
  duracion="15 min", dp=1, dm=1,
  materiales=["Una pelota liviana, blanda o de tela","Un espacio despejado y seguro"],
  preparacion="Despeja una zona del suelo de objetos duros o peligrosos. Si el piso es duro, pon una manta.",
  pasos=["Siéntate en el suelo frente al bebé, a poca distancia.","Hazle rodar la pelota despacio hacia sus manos.","Anímalo a empujarla o lanzarla de vuelta hacia ti.","Aléjala un poco para que gatee o camine a buscarla.","Celebra cada vez que la alcanza: «¡la atrapaste!»."],
  aprendizaje="Favorece el gateo, la marcha y la coordinación entre ojos y manos. Pasarse la pelota por turnos siembra las primeras nociones de juego compartido.",
  variantes="Usa una pelota con cascabel dentro o hazla rodar dentro de un túnel de cojines.",
  seguridad="Elige una pelota blanda y grande, que no quepa en la boca, y juega en una zona sin esquinas duras."),

 dict(n=19, slug="maracas-botella", tipo="recreativa",
  titulo="Maracas que suenan",
  gancho="Botellas con sorpresas dentro que suenan distinto al agitarlas.",
  duracion="10-15 min", dp=2, dm=1,
  materiales=["Botellas de plástico pequeñas con tapa","Rellenos sonoros (arroz, fideos, cascabeles, botones grandes)","Pegamento fuerte o cinta para sellar las tapas"],
  preparacion="Llena cada botella hasta un tercio con un material distinto y sella muy bien la tapa con pegamento y cinta. Prepara dos o tres maracas.",
  pasos=["Agita tú una maraca marcando un ritmo sencillo.","Dásela al bebé para que la sacuda a su manera.","Cambien de maraca y comparen los distintos sonidos.","Acompañen con una canción y muevan las maracas al compás.","Hagan pausas de silencio y vuelvan a sonar para jugar con el contraste."],
  aprendizaje="Desarrolla el sentido del ritmo, el oído y la coordinación al agitar. Asociar movimiento y sonido es base del lenguaje y de la música.",
  variantes="Usa botellas transparentes para que además vea moverse el relleno de colores.",
  seguridad="Sella las tapas a la perfección: el contenido suelto es peligro de asfixia. Revísalas antes de cada uso."),

 dict(n=20, slug="baile-panuelos", tipo="recreativa",
  titulo="Baile de pañuelos",
  gancho="Telas que vuelan y caen despacio al ritmo de la música.",
  duracion="10-15 min", dp=1, dm=1,
  materiales=["Pañuelos o telas finas y livianas","Música suave o alegre"],
  preparacion="Elige un par de pañuelos livianos y despeja un espacio para moverse. Pon música.",
  pasos=["Toma un pañuelo y muévelo en el aire frente al bebé.","Déjalo caer despacio y di «¡cae!» mientras flota hacia el suelo.","Dale un pañuelo para que lo agite, lo lance y lo recoja.","Bailen juntos moviendo las telas arriba y abajo con la música.","Termina escondiendo tu cara tras el pañuelo para un «cucú» final."],
  aprendizaje="Estimula el movimiento, el equilibrio y la expresión a través del cuerpo y la música. Seguir el vuelo de la tela ejercita la mirada y la coordinación.",
  variantes="Cambien el ritmo de la música: rápido para agitar fuerte, lento para mecerse despacio.",
  seguridad="Usa pañuelos pequeños y nunca cubras con ellos la cara del bebé por más de un instante."),

 dict(n=21, slug="soplar-plumas", tipo="recreativa",
  titulo="Plumas voladoras",
  gancho="Soplar para que una pluma flote es un juego que encanta y enseña a controlar el aire.",
  duracion="10 min", dp=1, dm=1,
  materiales=["Plumas livianas o trocitos de papel de seda","Una bandeja o mesa"],
  preparacion="Reúne unas pocas plumas grandes y livianas sobre una bandeja, a la altura del bebé.",
  pasos=["Sopla tú una pluma y deja que el bebé la vea flotar y caer.","Sostén una pluma frente a su boca y anímalo a soplar.","Celebra cada intento, aunque solo mueva el aire un poquito.","Atrapen juntos las plumas que caen al suelo.","Pónganle una pluma en la mano para que la deje caer desde lo alto."],
  aprendizaje="Ejercita el soplo, que fortalece los músculos de la boca usados al hablar y comer. Seguir la pluma con la vista mejora la atención y la coordinación.",
  variantes="Soplen las plumas a través de un tubo de cartón para dirigir mejor el aire.",
  seguridad="Vigila que no se lleve las plumas a la boca o la nariz; guárdalas al terminar."),

 dict(n=22, slug="tambor-globo", tipo="recreativa",
  titulo="Tambor de globo",
  gancho="Un tarro y un globo se convierten en un tambor que vibra al tocarlo.",
  duracion="10 min", dp=2, dm=1,
  materiales=["Un tarro o lata limpia de boca ancha","Un globo grande","Una tijera y cinta"],
  preparacion="Corta el cuello del globo y estira la parte ancha sobre la boca del tarro como una membrana tensa. Asegúrala con cinta alrededor.",
  pasos=["Muéstrale el tambor y dale un golpecito con la mano.","Deja que el bebé golpee la membrana y sienta cómo vibra.","Marca un ritmo simple y anímalo a imitarte.","Pongan un poco de arroz encima y vean cómo salta al golpear.","Canten una canción usando el tambor para llevar el compás."],
  aprendizaje="Desarrolla el ritmo, la coordinación y la relación causa-efecto entre golpe y sonido. Ver saltar el arroz introduce de forma lúdica la idea de vibración.",
  variantes="Usa tarros de distintos tamaños para descubrir que cada tambor suena más grave o más agudo.",
  seguridad="Revisa que el borde del tarro no tenga filo y supervisa por si la membrana se rompe."),

 dict(n=23, slug="empujar-caja", tipo="recreativa",
  titulo="A pasear empujando la caja",
  gancho="Una caja con peso se convierte en el primer andador del bebé.",
  duracion="15 min", dp=1, dm=1,
  materiales=["Una caja de cartón resistente","Algo de peso para poner dentro (libros, botellas)","Un suelo firme"],
  preparacion="Coloca un par de libros o botellas dentro de la caja para darle peso y estabilidad. Despeja un pasillo libre de obstáculos.",
  pasos=["Pon al bebé de pie detrás de la caja, sujetándola con las manos.","Anímalo a empujarla hacia adelante dando pasitos.","Camina a su lado para darle seguridad y atajar la caja si va muy rápido.","Marquen una meta sencilla: «vamos hasta el sillón».","Ajusta el peso si la caja resbala demasiado o cuesta moverla."],
  aprendizaje="Refuerza la fuerza de las piernas y el equilibrio en los primeros pasos. Empujar con un objetivo desarrolla la coordinación y la confianza para caminar.",
  variantes="Sienta un peluche dentro de la caja para que lo «lleve de paseo».",
  seguridad="Acompáñalo siempre; usa la caja solo en suelo firme y plano, lejos de escaleras."),

 dict(n=24, slug="esconder-vasos", tipo="juego",
  titulo="¿Dónde quedó?",
  gancho="Esconder un juguete bajo un vaso para descubrir que las cosas no desaparecen.",
  duracion="10 min", dp=1, dm=1,
  materiales=["Dos o tres vasos o tazas opacas","Un juguete pequeño que no quepa en la boca"],
  preparacion="Elige vasos opacos iguales y un objeto que le guste, lo bastante grande para no ser un riesgo.",
  pasos=["Muéstrale el juguete y déjalo a la vista.","Tápalo con un vaso mientras dices «¿dónde está?».","Anímalo a levantar el vaso y descubrir el juguete: «¡aquí está!».","Cuando lo logre, prueba con dos vasos y esconde el juguete en uno.","Mueve despacio los vasos para que siga con la mirada dónde quedó."],
  aprendizaje="Construye la permanencia del objeto: entender que algo sigue existiendo aunque no se vea. Es un gran paso del desarrollo cognitivo y reduce la angustia de separación.",
  variantes="Esconde el juguete bajo una tela o detrás de tu espalda para variar el desafío.",
  seguridad="Usa siempre un objeto grande que no quepa entero en la boca."),

 dict(n=25, slug="tubo-pelotas", tipo="juego",
  titulo="Tubo lanza-pelotas",
  gancho="Dejar caer una pelota por un tubo y verla aparecer por el otro lado.",
  duracion="10-15 min", dp=2, dm=1,
  materiales=["Un tubo de cartón (de papel de cocina o de regalo)","Pelotas pequeñas blandas o pompones grandes","Cinta para fijar el tubo"],
  preparacion="Fija el tubo en diagonal sobre una pared, un mueble o una caja, con la salida apuntando a un recipiente.",
  pasos=["Muéstrale cómo metes una pelota por la parte de arriba del tubo.","Observen juntos cómo aparece y cae por abajo.","Dale una pelota para que la introduzca él mismo.","Pon un recipiente en la salida para que las pelotas «aterricen» ahí.","Cuenten las pelotas mientras las van metiendo, una a una."],
  aprendizaje="Trabaja la coordinación ojo-mano y la relación causa-efecto al anticipar dónde saldrá la pelota. Meter objetos por una ranura afina la motricidad fina.",
  variantes="Inclina el tubo más o menos para que las pelotas salgan más rápido o más lento.",
  seguridad="Usa pelotas grandes que no quepan enteras en la boca y supervisa el juego."),

 dict(n=26, slug="caja-panuelos", tipo="juego",
  titulo="Caja de pañuelos sorpresa",
  gancho="Tirar de un pañuelo y descubrir que aparece otro, y otro, y otro más.",
  duracion="10 min", dp=2, dm=1,
  materiales=["Una caja de pañuelos vacía o un envase con tapa con ranura","Pañuelos de tela o telas livianas anudadas entre sí"],
  preparacion="Mete las telas dentro de la caja por la ranura, dejando una punta asomada. Puedes anudarlas entre sí para una cadena continua.",
  pasos=["Muéstrale la punta de tela que asoma y tira un poco para mostrarle la idea.","Anímalo a tirar él de la tela y a sacarla.","Celebra su sorpresa cuando aparece otra detrás.","Cuando vacíe la caja, vuelvan a meter las telas juntos.","Nombra los colores de cada tela a medida que salen."],
  aprendizaje="Afina la pinza de los dedos y la fuerza de las manos al tirar. Volver a llenar la caja desarrolla la motricidad fina y la paciencia.",
  variantes="Usa telas de distintas texturas y colores para sumar estímulo sensorial.",
  seguridad="Usa telas en lugar de pañuelos de papel y evita cordones largos alrededor del cuello."),

 dict(n=27, slug="clasificar-pelotas", tipo="juego",
  titulo="Grandes y chicas",
  gancho="Separar pelotas grandes de pequeñas: el primer juego de clasificar.",
  duracion="10-15 min", dp=1, dm=1,
  materiales=["Pelotas u objetos blandos de dos tamaños bien distintos","Dos canastas o recipientes"],
  preparacion="Reúne objetos claramente grandes y claramente pequeños (pero no tanto como para ser riesgo) y coloca dos canastas.",
  pasos=["Muéstrale una pelota grande y una chica, nombrando «grande» y «chica».","Pon una de cada en su canasta para mostrar la idea.","Dale las pelotas de una en una y anímalo a ponerlas donde van.","Acompaña sin corregir de más: lo importante es que manipule y observe.","Al terminar, vacíen todo y vuelvan a empezar si quiere."],
  aprendizaje="Introduce la comparación de tamaños y la idea de agrupar, base del pensamiento lógico y matemático. Trasladar objetos ejercita la coordinación.",
  variantes="Clasifiquen por color en lugar de por tamaño cuando ya domine el juego.",
  seguridad="Asegúrate de que incluso los objetos «pequeños» no quepan enteros en la boca."),

 dict(n=28, slug="encestar-pelotas", tipo="juego",
  titulo="A encestar",
  gancho="Lanzar pelotas blandas dentro de una caja: puntería y risas garantizadas.",
  duracion="10-15 min", dp=1, dm=1,
  materiales=["Una caja o canasta grande","Pelotas blandas, calcetines enrollados o pompones grandes","Un espacio despejado"],
  preparacion="Coloca la caja en el suelo y reúne las pelotas blandas en un montón cerca.",
  pasos=["Siéntate con el bebé frente a la caja, bien cerca.","Muéstrale cómo dejas caer una pelota dentro: «¡adentro!».","Dale una pelota y anímalo a meterla o lanzarla a la caja.","Celebra cada acierto con aplausos y palabras.","Aleja la caja poco a poco para hacerlo un poquito más difícil."],
  aprendizaje="Mejora la puntería, la coordinación ojo-mano y el control de la fuerza al lanzar. Apuntar a un objetivo desarrolla la concentración.",
  variantes="Usen una canasta más alta o cuelguen un aro para encestar de pie.",
  seguridad="Usa solo objetos blandos y livianos para lanzar y juega lejos de objetos frágiles."),

 dict(n=29, slug="cinco-lobitos", tipo="emocional",
  titulo="Canciones con gestos",
  gancho="Cinco lobitos, las palmas palmitas… canciones de toda la vida para reír juntos.",
  duracion="10 min", dp=1, dm=1,
  materiales=["Solo tus manos y tu voz"],
  preparacion="Recuerda dos o tres canciones de gestos sencillas. Busca un momento tranquilo y cercano.",
  pasos=["Sienta al bebé frente a ti o sobre tus piernas.","Canta una canción haciendo los gestos despacio y exagerados.","Repite la misma canción varias veces para que la anticipe.","Haz una pausa antes del gesto final y observa cómo se emociona.","Toma sus manitos y guíalas para que haga los gestos contigo."],
  aprendizaje="Fortalece el vínculo afectivo y el lenguaje a través del ritmo y la repetición. Anticipar los gestos desarrolla la memoria y la atención compartida.",
  variantes="Inventa gestos nuevos para sus canciones favoritas o cámbiale el nombre del personaje por el suyo.",
  seguridad="Adapta la intensidad a su ánimo: si se sobreexcita, baja el ritmo y la voz."),

 dict(n=30, slug="masaje-cancion", tipo="emocional",
  titulo="Masaje con canción",
  gancho="Caricias suaves y una canción tranquila para conectar y relajarse.",
  duracion="10-15 min", dp=1, dm=1,
  materiales=["Una manta o toalla suave","Aceite vegetal apto para bebés (opcional)","Un ambiente cálido y tranquilo"],
  preparacion="Elige un momento en que el bebé esté tranquilo, no recién comido. Calienta la habitación y ten todo a mano.",
  pasos=["Recuesta al bebé boca arriba sobre la manta, sin ropa o con poca.","Frota tus manos para entrarlas en calor y, si usas, ponte un poco de aceite.","Acaricia con suavidad sus piernas, brazos y pancita con movimientos lentos.","Acompaña cada caricia con una canción suave o con su nombre.","Observa sus señales: si disfruta, continúa; si se incomoda, detente."],
  aprendizaje="Refuerza el apego seguro y ayuda a regular las emociones y el sueño. El contacto piel con piel libera bienestar en el bebé y en quien lo cuida.",
  variantes="Convierte el masaje en parte de la rutina antes de dormir.",
  seguridad="Usa solo aceites aptos para bebés, evita la zona del cordón si es recién nacido y nunca masajees a la fuerza."),

 dict(n=31, slug="burrito-manta", tipo="emocional",
  titulo="Burrito en la manta",
  gancho="Envolverse en una manta y mecerse: contención y cariño en estado puro.",
  duracion="10 min", dp=1, dm=1,
  materiales=["Una manta suave y no muy gruesa"],
  preparacion="Elige una manta liviana y un espacio tranquilo en el suelo o la cama.",
  pasos=["Recuesta al bebé sobre el borde de la manta.","Envuélvelo con suavidad dejando siempre la cara y la cabeza libres.","Mécelo despacio de un lado a otro como un burrito.","Canta o háblale con voz calmada mientras se mece.","Destápalo con un «¡cucú!» y un abrazo final."],
  aprendizaje="La presión suave y el balanceo regulan el sistema nervioso y transmiten calma. Es un juego de contención que refuerza la confianza y el vínculo.",
  variantes="Haz rodar suavemente al «burrito» sobre la cama para que se desenvuelva solo.",
  seguridad="Deja siempre la cara y el cuello descubiertos, no aprietes y nunca lo dejes envuelto sin vigilancia."),

 dict(n=32, slug="partes-del-cuerpo", tipo="emocional",
  titulo="¿Dónde está la nariz?",
  gancho="Un juego de cosquillas para descubrir y nombrar las partes del cuerpo.",
  duracion="10 min", dp=1, dm=1,
  materiales=["Solo tus manos y tu voz","Un espejo (opcional)"],
  preparacion="Busca un momento de juego tranquilo, frente a frente.",
  pasos=["Toca tu propia nariz y di «esta es la nariz».","Toca con suavidad la nariz del bebé repitiendo la palabra.","Sigue con ojos, boca, orejas, manos y pies, nombrando cada parte.","Pregunta «¿dónde está la nariz?» y espera a que la busque o señale.","Termina con cosquillas suaves en la pancita y muchas risas."],
  aprendizaje="Desarrolla el lenguaje y el esquema corporal: saber que su cuerpo tiene partes con nombre. El contacto cariñoso refuerza el vínculo y la autoimagen.",
  variantes="Juéguenlo frente al espejo o sobre un muñeco para señalar las partes en otro cuerpo.",
  seguridad="Toca siempre con suavidad y respeta si no quiere que le toquen la cara ese día."),

 dict(n=33, slug="pelota-va-viene", tipo="emocional",
  titulo="La pelota va y viene",
  gancho="Rodar la pelota por turnos: el primer juego de compartir y esperar.",
  duracion="10 min", dp=1, dm=1,
  materiales=["Una pelota blanda de tamaño mediano","Un suelo cómodo"],
  preparacion="Siéntense en el suelo, uno frente al otro, con las piernas abiertas formando un canal.",
  pasos=["Haz rodar la pelota despacio hacia el bebé diciendo «¡va!».","Espera a que la detenga con las manos.","Anímalo a devolvértela rodando: «ahora a mamá».","Celebra cada ida y vuelta con entusiasmo.","Mantén el ritmo del turno para que entienda el «tú y yo»."],
  aprendizaje="Introduce el juego por turnos, base de la comunicación y la futura conversación. Esperar su turno y devolver la pelota desarrolla la atención compartida.",
  variantes="Súmense más personas formando un círculo para rodar la pelota entre todos.",
  seguridad="Usa una pelota blanda y juega en un espacio despejado y cómodo."),

 dict(n=34, slug="paseo-sonidos", tipo="naturaleza",
  titulo="Paseo de los sonidos",
  gancho="Salir a escuchar el mundo: pájaros, viento, autos y hojas.",
  duracion="15-20 min", dp=1, dm=1,
  materiales=["Un paseo al aire libre (patio, plaza o calle tranquila)"],
  preparacion="Elige un momento del día tranquilo y un lugar al aire libre seguro. Abriga al bebé según el clima.",
  pasos=["Carga o pasea al bebé por un lugar al aire libre, sin prisa.","Detente de vez en cuando y guarda silencio para escuchar.","Nombra los sonidos que aparecen: «un pajarito», «el viento», «un auto».","Imita algunos sonidos para que los relacione con su origen.","Señala lo que produce cada sonido cuando sea posible verlo."],
  aprendizaje="Afina el oído y la atención, y conecta sonidos con sus causas. Pasear y nombrar el entorno enriquece el lenguaje y el asombro por la naturaleza.",
  variantes="Lleven a casa un sonido favorito imitándolo, o salgan a escuchar la lluvia bajo techo.",
  seguridad="Protégelo del sol y el frío y mantén siempre un entorno tranquilo y seguro."),

 dict(n=35, slug="canasta-naturaleza", tipo="naturaleza",
  titulo="Tesoros de la naturaleza",
  gancho="Una canasta con hojas, piñas y piedras grandes para explorar el bosque en casa.",
  duracion="10-15 min", dp=2, dm=1,
  materiales=["Elementos naturales seguros y grandes (hojas grandes, piñas, piedras lisas, ramas cortas)","Una canasta o bandeja"],
  preparacion="Recoge en un paseo elementos naturales limpios y lo bastante grandes para no ser un riesgo. Lávalos y ponlos en la canasta.",
  pasos=["Sienta al bebé frente a la canasta de tesoros naturales.","Deja que tome y explore cada elemento a su ritmo.","Nombra lo que toca: «una hoja», «una piña áspera», «una piedra lisa».","Acompaña describiendo texturas, olores y formas.","Guarda la canasta para repetir la exploración otros días."],
  aprendizaje="Conecta al bebé con la naturaleza a través de los sentidos y enriquece su vocabulario. Comparar texturas y formas naturales estimula la observación.",
  variantes="Cambia los tesoros según la estación: hojas secas en otoño, flores en primavera.",
  seguridad="Usa solo elementos grandes y limpios; vigila de cerca para que no se los lleve a la boca."),

 dict(n=36, slug="pintar-con-agua", tipo="arte",
  titulo="Pintar con agua",
  gancho="Una brocha, agua y una pared: arte que aparece y se seca sin manchar nada.",
  duracion="15 min", dp=1, dm=1,
  materiales=["Una brocha gruesa o un rodillo pequeño","Un balde con un poco de agua","Una superficie segura (muro exterior, baldosa, vereda)"],
  preparacion="Busca un muro o suelo exterior que se pueda mojar sin problema. Llena el balde con poca agua.",
  pasos=["Moja la brocha en el agua y haz una marca en la pared para mostrarle.","Dale la brocha al bebé y anímalo a «pintar» con agua.","Observen cómo aparecen las marcas oscuras al mojar.","Vean cómo se secan y desaparecen con el sol.","Pinten formas grandes, líneas y manchas a su antojo."],
  aprendizaje="Ejercita el brazo y la coordinación con el gesto amplio de pintar, sin la frustración de ensuciar. Ver aparecer y secarse el agua introduce la idea de cambio.",
  variantes="Usen esponjas, rodillos o las propias manos mojadas para variar las marcas.",
  seguridad="Usa poca agua, vigila que el suelo mojado no resbale y mantén el balde a baja altura."),
]

ORD = ["id","orden","edad","tipo","titulo","gancho","duracion","dif_prep","dif_materiales",
       "materiales","preparacion","pasos","aprendizaje","variantes","seguridad","imagen"]

def dump(d):
    return "\n".join(
        (yaml.safe_dump({k: d[k]}, allow_unicode=True, default_flow_style=False, sort_keys=False, width=100).rstrip())
        for k in ORD) + "\n"

for a in A:
    id_ = f"0a2-{a['n']:02d}"
    rec = dict(id=id_, orden=a["n"], edad="0-2", tipo=a["tipo"], titulo=a["titulo"],
               gancho=a["gancho"], duracion=a["duracion"], dif_prep=a["dp"], dif_materiales=a["dm"],
               materiales=a["materiales"], preparacion=a["preparacion"], pasos=a["pasos"],
               aprendizaje=a["aprendizaje"], variantes=a["variantes"], seguridad=a["seguridad"],
               imagen=f"{id_}.png")
    (DST / f"{id_}-{a['slug']}.yaml").write_text(dump(rec), encoding="utf-8")
    print("escrito", id_, a["titulo"])
print("Total:", len(A))
