#!/usr/bin/env python3
"""Crea las 24 actividades nuevas del rango 6-8 (ids 6a8-13 .. 6a8-36)."""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
DST = ROOT / "data" / "activities"

A = [
 dict(n=13, slug="cristales-sal", tipo="experimento",
  titulo="Cristales de sal",
  gancho="Cultivar tus propios cristales y verlos crecer día a día como pequeñas joyas.",
  duracion="20 min + varios días", dp=1, dm=1,
  materiales=["Agua caliente (la maneja un adulto)","Sal o azúcar en abundancia","Un frasco de vidrio","Un hilo o un palito","Un lápiz para cruzar sobre el frasco"],
  preparacion="Un adulto prepara agua caliente y disuelve toda la sal posible, hasta que ya no se disuelva más.",
  pasos=["Disuelvan sal en el agua caliente hasta saturarla.","Aten un hilo a un lápiz y déjenlo colgando dentro del frasco sin tocar el fondo.","Coloquen el frasco en un lugar tranquilo donde nadie lo mueva.","Observen cada día cómo se forman cristales sobre el hilo.","Anoten o dibujen el tamaño de los cristales día a día."],
  aprendizaje="Muestra cómo, al evaporarse el agua, la sal disuelta vuelve a formar cristales sólidos. Observar el cambio durante días enseña paciencia y método científico.",
  variantes="Comparen cristales de sal y de azúcar, o tiñan el agua para cristales de colores.",
  seguridad="Un adulto maneja el agua caliente; el resultado no se come."),

 dict(n=14, slug="slime", tipo="experimento",
  titulo="Slime casero",
  gancho="Una masa viscosa que se estira, se escurre y nunca deja de sorprender.",
  duracion="20 min", dp=1, dm=2,
  materiales=["Cola blanca (pegamento escolar)","Bicarbonato de sodio","Solución para lentes de contacto (con borato)","Colorante o purpurina","Un bol y una cuchara"],
  preparacion="Reúne todo sobre una mesa protegida. Mide media taza de cola blanca en el bol.",
  pasos=["Viertan la cola en el bol y agreguen color o purpurina al gusto.","Añadan una cucharadita de bicarbonato y mezclen bien.","Agreguen la solución de a poco, revolviendo sin parar.","Sigan hasta que la mezcla se despegue del bol y se vuelva elástica.","Amasen con las manos hasta lograr la textura justa."],
  aprendizaje="Introduce ideas de química: dos líquidos forman una masa elástica al unir sus partículas. Ajustar la receta enseña a observar, medir y corregir.",
  variantes="Prueben slime magnético con limaduras de hierro o uno que brille en la oscuridad.",
  seguridad="No se come; lávense las manos al terminar y eviten el contacto con los ojos."),

 dict(n=15, slug="huevo-flota", tipo="experimento",
  titulo="El huevo que flota",
  gancho="¿Un huevo puede flotar? Con el truco del agua salada, sí.",
  duracion="15 min", dp=1, dm=1,
  materiales=["Dos vasos altos","Agua","Sal en abundancia","Un huevo (o dos)","Una cuchara"],
  preparacion="Llena los dos vasos con agua. Deja uno con agua normal.",
  pasos=["Pongan el huevo en el vaso de agua normal y observen que se hunde.","En el otro vaso, disuelvan varias cucharadas de sal.","Predigan qué pasará al poner el huevo en el agua salada.","Coloquen el huevo en el agua salada y vean cómo flota.","Prueben agregar más o menos sal y observen los cambios."],
  aprendizaje="Demuestra que el agua salada es más densa y puede sostener objetos que en agua normal se hunden. Predecir y comprobar afianza el razonamiento científico.",
  variantes="Logren que el huevo quede a media altura mezclando con cuidado agua salada y dulce.",
  seguridad="No beban el agua salada y manejen el huevo con cuidado para no romperlo."),

 dict(n=16, slug="periscopio", tipo="experimento",
  titulo="Periscopio de cartón",
  gancho="Un tubo con espejos para espiar por encima de los muebles, como en un submarino.",
  duracion="30-40 min", dp=2, dm=2,
  materiales=["Una caja de cartón alargada o un envase de leche","Dos espejos pequeños iguales","Tijeras y cinta","Regla y lápiz"],
  preparacion="Reúne los materiales y, con ayuda, marca dónde irán las aberturas y los espejos en diagonal.",
  pasos=["Hagan una abertura en la parte de arriba y otra abajo, en lados opuestos.","Coloquen un espejo en diagonal frente a cada abertura, mirándose entre sí.","Fíjenlos con cinta en un ángulo de 45 grados.","Cierren el tubo y miren por la abertura de abajo.","Prueben espiar por encima de una mesa o detrás de un mueble."],
  aprendizaje="Enseña que la luz rebota en los espejos y cambia de dirección, base de la óptica. Construir y ajustar los ángulos desarrolla la lógica y la motricidad.",
  variantes="Decoren el periscopio como un submarino o úsenlo para mirar a la vuelta de una esquina.",
  seguridad="Un adulto ayuda con los cortes y maneja los espejos para evitar bordes filosos."),

 dict(n=17, slug="brujula", tipo="experimento",
  titulo="Brújula casera",
  gancho="Una aguja flotante que siempre apunta al norte, como por arte de magia.",
  duracion="20 min", dp=2, dm=1,
  materiales=["Una aguja de coser","Un imán","Un trozo de corcho o una hoja","Un bol con agua"],
  preparacion="Un adulto frota la aguja con el imán siempre en la misma dirección, unas treinta veces, para imantarla.",
  pasos=["Imanten la aguja frotándola con el imán siempre hacia el mismo lado.","Claven la aguja en un trozo de corcho o pónganla sobre una hoja.","Hagan flotar el corcho con la aguja en el bol con agua.","Observen cómo la aguja gira y se detiene apuntando al norte.","Comparen con una brújula real o con el mapa del celular."],
  aprendizaje="Muestra que la Tierra es un gran imán y que una aguja imantada se alinea con su campo. Construir un instrumento que funciona es muy motivador.",
  variantes="Acerquen otro imán y observen cómo la aguja se desvía de su dirección.",
  seguridad="Un adulto maneja la aguja; cuidado con los pinchazos."),

 dict(n=18, slug="twister-casero", tipo="recreativa",
  titulo="Twister casero",
  gancho="Manos y pies a los colores: a enredarse sin caer en este clásico hecho en casa.",
  duracion="20-30 min", dp=2, dm=1,
  materiales=["Una sábana vieja o plástico grande","Témpera o cartulinas de colores para hacer círculos","Un dado o ruleta de colores y partes del cuerpo"],
  preparacion="Pinta o pega filas de círculos de cuatro colores sobre la sábana. Prepara una ruleta que combine un color y una parte del cuerpo.",
  pasos=["Extiendan la sábana en el suelo y dejen la ruleta a un lado.","Por turnos, giren la ruleta: «mano derecha, azul».","Cada jugador pone esa parte del cuerpo en un círculo de ese color.","Sigan girando: las posturas se vuelven cada vez más enredadas.","Pierde quien se cae o apoya una rodilla; el último en pie gana."],
  aprendizaje="Desarrolla el equilibrio, la flexibilidad y el conocimiento de izquierda y derecha. Seguir instrucciones y reírse juntos fortalece la convivencia.",
  variantes="Agreguen instrucciones divertidas como «codo» o «oreja» para complicar el juego.",
  seguridad="Jueguen sobre una superficie que no resbale y respeten los límites del cuerpo de cada uno."),

 dict(n=19, slug="badminton-globo", tipo="recreativa",
  titulo="Bádminton con globo",
  gancho="Raquetas de cartón y un globo: un partido lento y divertido para interiores.",
  duracion="20 min", dp=2, dm=1,
  materiales=["Platos o cartón para las raquetas","Palitos de helado o reglas para los mangos","Un globo","Cinta"],
  preparacion="Hagan raquetas pegando un palito a un plato o recorte de cartón. Inflen un globo.",
  pasos=["Marquen una línea imaginaria o pongan una cuerda como red.","Golpeen el globo con la raqueta para pasarlo al otro lado.","El globo no puede tocar el suelo del propio campo.","Cuenten los puntos cuando el globo cae en el campo contrario.","Jueguen al mejor de varios puntos y cambien de lado."],
  aprendizaje="Mejora la coordinación ojo-mano y los reflejos con un objeto lento y seguro. Jugar por turnos y llevar el puntaje suma habilidades sociales y de cálculo.",
  variantes="Jueguen de forma cooperativa: cuenten cuántos golpes logran sin que el globo caiga.",
  seguridad="Jueguen en un espacio despejado; recojan los globos rotos de inmediato por ser peligro de asfixia."),

 dict(n=20, slug="punteria-tejo", tipo="recreativa",
  titulo="Juego de puntería",
  gancho="Lanzar saquitos a una diana de cajas para sumar puntos: pura puntería.",
  duracion="20 min", dp=2, dm=1,
  materiales=["Cajas o recipientes de distintos tamaños","Saquitos de tela rellenos de legumbres o calcetines enrollados","Cartulina para los números"],
  preparacion="Coloquen las cajas a distintas distancias y asignen a cada una un puntaje según su dificultad.",
  pasos=["Marquen una línea de lanzamiento en el suelo.","Asignen más puntos a las cajas más lejanas o pequeñas.","Por turnos, lancen tres saquitos intentando encestar.","Sumen los puntos de cada ronda en una hoja.","Gana quien acumule más puntos tras varias rondas."],
  aprendizaje="Afina la puntería, el control de la fuerza y el cálculo al sumar los puntajes. Esperar el turno y aceptar el resultado fortalece el juego limpio.",
  variantes="Cuelguen aros o cajas a distintas alturas para variar el desafío.",
  seguridad="Usen saquitos blandos y jueguen lejos de objetos frágiles."),

 dict(n=21, slug="aviones-papel", tipo="recreativa",
  titulo="Campeonato de aviones de papel",
  gancho="Plegar, lanzar y medir: ¿qué avión vuela más lejos?",
  duracion="30 min", dp=1, dm=1,
  materiales=["Hojas de papel","Una cinta métrica o pasos para medir","Lápiz para anotar"],
  preparacion="Reúne varias hojas y despeja un pasillo o el patio para los lanzamientos.",
  pasos=["Plieguen distintos modelos de avión de papel.","Decoren cada avión para reconocerlo.","Por turnos, lancen desde una misma línea de salida.","Midan cuánto voló cada avión y anótenlo.","Comparen los modelos y descubran cuál vuela mejor y por qué."],
  aprendizaje="Introduce nociones de aerodinámica al comparar formas y vuelos. Medir, anotar y comparar resultados es hacer ciencia de forma divertida.",
  variantes="Modifiquen un avión (más alas, un clip de peso) y comprueben cómo cambia su vuelo.",
  seguridad="Lancen siempre hacia un espacio abierto, nunca hacia la cara de otros."),

 dict(n=22, slug="tres-en-raya", tipo="juego",
  titulo="Tres en raya gigante",
  gancho="El clásico gato, pero en grande y con fichas hechas a mano.",
  duracion="20 min", dp=2, dm=1,
  materiales=["Cartulina o cinta para el tablero","Tapas, piedras o cartones para las fichas (dos grupos distintos)"],
  preparacion="Dibujen o armen con cinta un tablero de tres por tres casillas. Preparen cinco fichas de cada tipo.",
  pasos=["Repartan un grupo de fichas a cada jugador.","Por turnos, coloquen una ficha en una casilla vacía.","El objetivo es alinear tres fichas propias en fila, columna o diagonal.","Bloqueen las jugadas del rival mientras buscan su propia línea.","Quien logre tres en raya gana la partida."],
  aprendizaje="Desarrolla el pensamiento estratégico y la anticipación de las jugadas del otro. Es un primer juego de lógica ideal para razonar por turnos.",
  variantes="Hagan un tres en raya humano usando aros en el patio y a las personas como fichas.",
  seguridad="Usen fichas grandes y seguras, sobre todo si hay hermanos pequeños cerca."),

 dict(n=23, slug="batalla-naval", tipo="juego",
  titulo="Batalla naval de papel",
  gancho="Esconder barcos en una cuadrícula y adivinar dónde está la flota enemiga.",
  duracion="30 min", dp=2, dm=1,
  materiales=["Hojas cuadriculadas","Lápices","Una carpeta o libro para no verse los tableros"],
  preparacion="Dibujen dos cuadrículas por jugador con filas de letras y columnas de números.",
  pasos=["Cada uno dibuja en secreto sus barcos en una cuadrícula.","Por turnos, digan una coordenada para atacar: «B-4».","El rival responde «agua» o «tocado» según corresponda.","Marquen los aciertos y fallos en la segunda cuadrícula.","Gana quien hunda primero todos los barcos del otro."],
  aprendizaje="Trabaja las coordenadas, la memoria y la estrategia de búsqueda. Ubicar puntos en una cuadrícula es una base divertida de la geometría.",
  variantes="Usen barcos de distintos tamaños o agreguen un submarino con poderes especiales.",
  seguridad="Recuerden no espiar el tablero del rival para que el juego sea justo."),

 dict(n=24, slug="domino-casero", tipo="juego",
  titulo="Dominó casero",
  gancho="Fichas hechas a mano para encadenar puntos y jugar en familia.",
  duracion="30 min", dp=2, dm=1,
  materiales=["Cartón firme para las fichas","Regla, lápiz y plumones","Tijeras"],
  preparacion="Recorten fichas rectangulares iguales y dibujen en cada mitad de cero a seis puntos, formando todas las combinaciones.",
  pasos=["Repartan las fichas y dejen el resto en el pozo, boca abajo.","Por turnos, encadenen una ficha que coincida en los puntos.","Si no pueden jugar, roben una ficha del pozo.","Cuenten en voz alta los puntos para encontrar las coincidencias.","Gana quien se quede primero sin fichas."],
  aprendizaje="Refuerza el reconocimiento de cantidades y la correspondencia uno a uno. Planear las jugadas y esperar el turno desarrolla la lógica y la paciencia.",
  variantes="Hagan un dominó de dibujos o de colores para los más pequeños de la casa.",
  seguridad="Usen tijeras de punta redonda y un adulto ayuda con los recortes."),

 dict(n=25, slug="mimica", tipo="juego",
  titulo="El juego de la mímica",
  gancho="Actuar sin hablar para que los demás adivinen: risas garantizadas.",
  duracion="20-30 min", dp=1, dm=1,
  materiales=["Papelitos con palabras o dibujos (animales, oficios, acciones)","Un recipiente para sortearlos","Un reloj o cronómetro"],
  preparacion="Escriban o dibujen en papelitos cosas fáciles de actuar y dóblenlos en el recipiente.",
  pasos=["Por turnos, saquen un papelito sin mostrarlo a nadie.","Representen la palabra solo con gestos, sin hablar ni hacer ruidos.","Los demás tienen un minuto para adivinar de qué se trata.","Quien acierte gana un punto y pasa a actuar.","Sigan jugando por rondas hasta que todos hayan actuado."],
  aprendizaje="Estimula la expresión corporal, la creatividad y la comunicación no verbal. Interpretar y adivinar gestos desarrolla la empatía y la atención.",
  variantes="Jueguen por equipos o limiten las categorías a películas o cuentos conocidos.",
  seguridad="Acompañen con paciencia a quien le cueste actuar; lo importante es participar."),

 dict(n=26, slug="atrapasuenos", tipo="arte",
  titulo="Atrapasueños",
  gancho="Un aro con hilos y plumas para colgar sobre la cama y atrapar los buenos sueños.",
  duracion="40 min", dp=2, dm=2,
  materiales=["Un aro (plato de cartón con el centro recortado)","Lana o hilo","Cuentas, plumas y cintas","Pegamento"],
  preparacion="Prepara el aro y reúne la lana, las cuentas y las plumas para decorar.",
  pasos=["Aten un extremo de la lana al aro y crucen el centro formando una telaraña.","Vayan pasando la lana de un punto a otro, ensartando alguna cuenta.","Aten cintas y plumas colgando de la parte de abajo del aro.","Hagan un lazo arriba para poder colgarlo.","Cuélguenlo cerca de la cama y conversen sobre los sueños."],
  aprendizaje="Combina motricidad fina, paciencia y creatividad al tejer y decorar. Conocer una tradición distinta enriquece la mirada cultural.",
  variantes="Usen colores según el estado de ánimo o sumen pequeños dibujos colgantes.",
  seguridad="Un adulto ayuda a recortar el centro del aro y supervisa el uso de pegamento."),

 dict(n=27, slug="acuarela-sal", tipo="arte",
  titulo="Acuarela con sal",
  gancho="Pintar con acuarela y espolvorear sal para crear texturas mágicas y brillantes.",
  duracion="25 min", dp=1, dm=1,
  materiales=["Acuarelas o témpera aguada","Papel grueso","Sal gruesa","Pinceles y agua"],
  preparacion="Protege la mesa y prepara los colores bien diluidos con agua.",
  pasos=["Pinten el papel con acuarela bien mojada, sin dejar secar.","Mientras está húmedo, espolvoreen sal sobre la pintura.","Observen cómo la sal absorbe el agua y crea texturas estrelladas.","Dejen secar por completo la obra.","Sacudan la sal seca y descubran los efectos que quedaron."],
  aprendizaje="Muestra cómo la sal absorbe el agua y modifica la pintura, uniendo arte y ciencia. Experimentar con materiales desarrolla la creatividad y la observación.",
  variantes="Prueben con distintos tipos de sal o combinen varios colores que se mezclen al mojarse.",
  seguridad="Usen pinturas no tóxicas y protejan la ropa con un delantal."),

 dict(n=28, slug="origami-animales", tipo="arte",
  titulo="Origami de animales",
  gancho="Doblar papel hasta que aparezca un perro, una rana o un pájaro.",
  duracion="30 min", dp=1, dm=1,
  materiales=["Hojas de papel cuadradas","Plumones para los detalles","Una guía de dobleces (opcional)"],
  preparacion="Recorten hojas cuadradas y elijan una figura sencilla para empezar, como la cara de un perro.",
  pasos=["Sigan paso a paso los dobleces de la figura elegida.","Marquen bien cada pliegue pasando la uña por el borde.","Ayúdense entre todos cuando un paso sea más difícil.","Dibujen ojos, hocico y detalles al terminar.","Armen una colección de animales y jueguen con ellos."],
  aprendizaje="Desarrolla la motricidad fina, la atención a las instrucciones y la noción espacial. Seguir una secuencia de pasos entrena la concentración y la paciencia.",
  variantes="Hagan un móvil colgando varios animales o inventen una historia con ellos.",
  seguridad="Actividad muy segura; cuiden solo de no frustrarse y pedir ayuda cuando haga falta."),

 dict(n=29, slug="piedras-pintadas", tipo="arte",
  titulo="Piedras pintadas",
  gancho="Transformar piedras lisas en mariquitas, monstruos o mensajes de colores.",
  duracion="30 min + secado", dp=1, dm=1,
  materiales=["Piedras lisas y limpias","Témpera o pintura acrílica","Pinceles finos","Barniz o cola transparente (opcional)"],
  preparacion="Laven y sequen las piedras. Protejan la mesa con papel de diario.",
  pasos=["Observen la forma de cada piedra e imaginen en qué puede convertirse.","Pinten primero un fondo de color y déjenlo secar.","Agreguen los detalles con pincel fino: ojos, puntos, dibujos.","Dejen secar bien la pintura.","Si quieren, sellen con una capa de barniz para protegerlas."],
  aprendizaje="Estimula la creatividad y la observación al ver figuras en las formas naturales. Pintar detalles finos afina la motricidad y la concentración.",
  variantes="Escondan las piedras pintadas en una plaza para que otros las encuentren.",
  seguridad="Usen pinturas no tóxicas y un adulto supervisa si usan barniz."),

 dict(n=30, slug="diario-gratitud", tipo="emocional",
  titulo="Diario de gratitud",
  gancho="Un cuaderno para anotar cada día tres cosas buenas y entrenar la mirada positiva.",
  duracion="10 min al día", dp=1, dm=1,
  materiales=["Un cuaderno o libreta","Lápices de colores","Stickers para decorar (opcional)"],
  preparacion="Decoren juntos la portada del cuaderno y elijan un momento fijo del día, como antes de dormir.",
  pasos=["Cada día, piensen en tres cosas buenas que les pasaron.","Escríbanlas o dibújenlas en el cuaderno.","Conversen sobre por qué los hicieron sentir bien.","Lean de vez en cuando las páginas anteriores.","Mantengan el hábito como un ritual de fin del día."],
  aprendizaje="Cultiva la gratitud y el optimismo, hábitos que protegen el bienestar emocional. Escribir sobre lo bueno ayuda a procesar el día y a dormir mejor.",
  variantes="Hagan un diario de gratitud familiar donde cada uno aporte su frase del día.",
  seguridad="No corrijan la ortografía ni juzguen lo que escriben: el espacio es libre y seguro."),

 dict(n=31, slug="buzon-familiar", tipo="emocional",
  titulo="El buzón familiar",
  gancho="Un buzón para dejarse mensajes cariñosos entre todos los de la casa.",
  duracion="30 min + uso diario", dp=2, dm=1,
  materiales=["Una caja de cartón con una ranura","Papel y lápices","Material para decorar"],
  preparacion="Decoren juntos la caja como un buzón y déjenla en un lugar común con papel al lado.",
  pasos=["Expliquen que cualquiera puede dejar un mensaje para otro.","Escriban notas de cariño, agradecimientos o cosas que quieran contar.","Doblen el papel y métanlo por la ranura del buzón.","Una vez por semana, abran el buzón y lean los mensajes juntos.","Respondan los mensajes dejando nuevas notas."],
  aprendizaje="Fomenta la comunicación afectuosa y la expresión de emociones por escrito. Recibir mensajes de cariño fortalece la autoestima y los vínculos familiares.",
  variantes="Usen el buzón también para proponer planes o resolver pequeños desacuerdos con calma.",
  seguridad="Acuerden que es un espacio de respeto: solo mensajes amables y constructivos."),

 dict(n=32, slug="ruleta-calma", tipo="emocional",
  titulo="La ruleta de la calma",
  gancho="Una ruleta con estrategias para calmarse cuando las emociones se desbordan.",
  duracion="30 min", dp=2, dm=1,
  materiales=["Cartulina","Un broche o lápiz como eje","Plumones","Tijeras"],
  preparacion="Dibujen un círculo dividido en porciones y conversen sobre qué ayuda a calmarse.",
  pasos=["Escriban o dibujen una estrategia en cada porción: respirar, contar hasta diez, abrazar, beber agua, saltar.","Coloquen una flecha giratoria en el centro con un broche.","Cuando alguien se sienta enojado o nervioso, giren la ruleta.","Practiquen juntos la estrategia que salió.","Usen la ruleta cada vez que haga falta recuperar la calma."],
  aprendizaje="Entrega herramientas concretas para autorregular las emociones intensas. Practicar la calma en momentos tranquilos facilita usarla cuando de verdad se necesita.",
  variantes="Adapten las estrategias a lo que mejor le funcione a cada niño.",
  seguridad="Validen siempre la emoción antes de calmarla: sentir rabia o miedo es normal."),

 dict(n=33, slug="herbario", tipo="naturaleza",
  titulo="Mi primer herbario",
  gancho="Recoger hojas y flores, prensarlas y armar una colección de la naturaleza.",
  duracion="30 min + días de prensado", dp=2, dm=1,
  materiales=["Hojas y flores recogidas en un paseo","Libros pesados para prensar","Papel absorbente","Una libreta o cartulina","Pegamento"],
  preparacion="Salgan a recoger hojas y flores variadas, evitando dañar las plantas.",
  pasos=["Coloquen cada hoja o flor entre papel absorbente.","Pónganlas bajo libros pesados para prensarlas.","Esperen varios días hasta que estén planas y secas.","Péguenlas en la libreta y escriban dónde y cuándo las encontraron.","Comparen formas, bordes y colores de las distintas hojas."],
  aprendizaje="Conecta con la naturaleza y enseña a observar y clasificar las plantas. Registrar y comparar desarrolla la observación científica y el cuidado del entorno.",
  variantes="Investiguen el nombre de cada planta o agreguen calcos de cortezas de árboles.",
  seguridad="Recojan solo del suelo o con permiso, sin arrancar plantas, y eviten las que no conozcan."),

 dict(n=34, slug="estacion-meteo", tipo="naturaleza",
  titulo="Estación del tiempo",
  gancho="Instrumentos caseros para medir la lluvia y el viento como un meteorólogo.",
  duracion="40 min + observación", dp=2, dm=1,
  materiales=["Una botella de plástico para el pluviómetro","Una regla","Cartulina y un palito para la veleta","Un calendario para anotar"],
  preparacion="Con ayuda, corten la botella para hacer un recipiente que mida la lluvia, y armen una veleta que gire con el viento.",
  pasos=["Coloquen el pluviómetro al aire libre, en un lugar despejado.","Marquen una escala en centímetros con la regla.","Pongan la veleta donde el viento la haga girar.","Cada día, anoten la lluvia caída y la dirección del viento.","Al cabo de unas semanas, comparen los datos y busquen patrones."],
  aprendizaje="Introduce la observación del clima y el registro de datos a lo largo del tiempo. Medir y comparar enseña constancia y pensamiento científico.",
  variantes="Sumen un termómetro y registren también la temperatura de cada día.",
  seguridad="Un adulto corta la botella; coloquen los instrumentos en un lugar seguro."),

 dict(n=35, slug="hotel-insectos", tipo="naturaleza",
  titulo="Hotel de insectos",
  gancho="Un refugio hecho con palitos y piñas para invitar a los bichos del jardín.",
  duracion="40 min + observación", dp=2, dm=1,
  materiales=["Una caja o envase abierto","Ramitas, piñas, hojas secas y tubos de cartón","Cuerda para colgar"],
  preparacion="Reúnan materiales naturales secos y una caja que sirva de estructura.",
  pasos=["Rellenen la caja con haces de ramitas, piñas y tubos de cartón.","Dejen huecos de distintos tamaños donde puedan refugiarse los insectos.","Coloquen o cuelguen el hotel en un rincón tranquilo del jardín.","Observen con paciencia qué bichos llegan a vivir o esconderse.","Anoten o dibujen los visitantes que vayan descubriendo."],
  aprendizaje="Enseña la importancia de los insectos en la naturaleza y fomenta su cuidado. Observar la vida del jardín desarrolla el respeto por los seres vivos.",
  variantes="Investiguen qué insecto vive en cada tipo de hueco y por qué.",
  seguridad="Observen sin tocar los insectos y lávense las manos después de manipular materiales."),

 dict(n=36, slug="reloj-sol", tipo="naturaleza",
  titulo="Reloj de sol",
  gancho="Medir el paso de las horas con la sombra de un palito, como en la antigüedad.",
  duracion="20 min + un día de sol", dp=2, dm=1,
  materiales=["Un palito o lápiz","Un plato, cartón o un trozo de patio","Piedritas o tiza para marcar","Un reloj para comparar"],
  preparacion="Elijan un lugar soleado donde el sol dé todo el día y claven el palito en posición vertical.",
  pasos=["Claven el palito en el centro de la base, bien derecho.","Cada hora, marquen dónde cae la punta de la sombra.","Escriban junto a cada marca la hora correspondiente.","Al día siguiente, lean la hora mirando la sombra.","Comparen su reloj de sol con un reloj normal."],
  aprendizaje="Muestra cómo el movimiento del sol marca el paso del tiempo y mueve las sombras. Construir un instrumento antiguo conecta ciencia, historia y observación.",
  variantes="Comparen la longitud de la sombra a distintas horas y en distintas estaciones.",
  seguridad="No miren directamente al sol y usen protección si están mucho rato al aire libre."),
]

ORD = ["id","orden","edad","tipo","titulo","gancho","duracion","dif_prep","dif_materiales",
       "materiales","preparacion","pasos","aprendizaje","variantes","seguridad","imagen"]

def dump(d):
    return "\n".join(
        (yaml.safe_dump({k: d[k]}, allow_unicode=True, default_flow_style=False, sort_keys=False, width=100).rstrip())
        for k in ORD) + "\n"

for a in A:
    id_ = f"6a8-{a['n']:02d}"
    rec = dict(id=id_, orden=a["n"], edad="6-8", tipo=a["tipo"], titulo=a["titulo"],
               gancho=a["gancho"], duracion=a["duracion"], dif_prep=a["dp"], dif_materiales=a["dm"],
               materiales=a["materiales"], preparacion=a["preparacion"], pasos=a["pasos"],
               aprendizaje=a["aprendizaje"], variantes=a["variantes"], seguridad=a["seguridad"],
               imagen=f"{id_}.png")
    (DST / f"{id_}-{a['slug']}.yaml").write_text(dump(rec), encoding="utf-8")
    print("escrito", id_, a["titulo"])
print("Total:", len(A))
