# -*- coding: utf-8 -*-
"""Prompts de imagen (en inglés, para evitar texto incrustado) de cada actividad.
PROMPTS[id] = {accent, hero, mat, steps[3]}. Lo consume scripts/gen_images.py.
'hero' es opcional para las actividades cuyo hero ya estaba generado.
"""
EXP, SEN, REC, JUE, EMO, ART, NAT = (
    "#3E6E94", "#7E57A6", "#E8744F", "#2E7D5B", "#D24D6E", "#F2A03D", "#5B9E4A")

PROMPTS = {
 # ---------------- 0 a 2 (existentes 01-12) ----------------
 "0a2-01": dict(accent=SEN,
   hero="exploring a woven basket filled with everyday wooden spoons, fabric scraps and natural objects; the baby reaches in with curiosity",
   mat="a low wicker basket, a wooden spoon, a sponge, a small metal cup, a fabric scrap, a soft fabric ball, a blanket",
   steps=["a baby sitting on a blanket with a treasure basket within reach",
          "a baby's hands lifting a wooden spoon out of a basket",
          "a parent's hand and a baby touching a shiny metal cup together"]),
 "0a2-02": dict(accent=SEN,
   hero="blowing soft soap bubbles that float and shimmer while the baby reaches up to touch them, delighted",
   mat="a bowl of warm soapy water and a bubble wand",
   steps=["a parent holding a baby comfortably on their lap",
          "a parent gently blowing soap bubbles into the air",
          "a baby reaching up to pop a floating soap bubble"]),
 "0a2-03": dict(accent=SEN,
   hero="gazing at a clear sensory bottle filled with water, glitter and floating shapes, calm and mesmerized, the parent holding it",
   mat="a small clear plastic bottle, water, colorful buttons, sequins and glitter, glue to seal the cap",
   steps=["a parent shaking a glitter sensory bottle gently",
          "a clear sensory bottle rolling slowly across the floor",
          "a baby's hands holding and turning a glitter bottle"]),
 "0a2-04": dict(accent=SEN,
   hero="splashing and pouring water between cups and small containers with a spoon, having fun",
   mat="a low basin with a little water, cups, mugs and spoons of different sizes, a towel",
   steps=["a baby sitting in front of a low basin of water",
          "small hands pouring water from a cup into a basin",
          "a baby splashing water between two small containers"]),
 "0a2-05": dict(accent=SEN,
   hero="touching a soft patchwork blanket made of many different fabric textures",
   mat="scraps of different fabrics, a base blanket, needle and thread",
   steps=["a baby lying on a soft patchwork texture blanket",
          "a parent guiding a baby's hand over fabric patches",
          "a baby's hand touching a fluffy fabric square"]),
 "0a2-06": dict(accent=EMO,
   hero="playing peekaboo, the parent hiding and reappearing behind their hands while the baby giggles",
   mat="a thin soft scarf",
   steps=["a parent hiding their face behind both hands",
          "a parent peeking out from behind a thin scarf, smiling",
          "a happy baby reaching toward a smiling parent"]),
 "0a2-07": dict(accent=EMO,
   hero="in front of a mirror making happy faces and discovering their own reflection together",
   mat="a safe unbreakable mirror",
   steps=["a parent holding a baby in front of a mirror",
          "a parent pointing at a baby's reflection in a mirror",
          "a parent making a happy face in a mirror with a baby"]),
 "0a2-08": dict(accent=REC,
   hero="making music with pots, wooden spoons and tins used as drums, joyful and lively",
   mat="pots and plastic containers, wooden spoons, a sealed jar with rice inside",
   steps=["a baby sitting among pots and wooden spoons on the floor",
          "small hands tapping a pot with a wooden spoon",
          "a baby shaking a homemade rice maraca jar"]),
 "0a2-09": dict(accent=REC,
   hero="crawling and climbing over a soft course of cushions and blankets, the parent encouraging",
   mat="cushions and pillows of different sizes, blankets, open cardboard boxes",
   steps=["a baby at the start of a soft cushion course, parent encouraging",
          "a baby climbing over a big soft cushion",
          "a baby crawling under a blanket tunnel"]),
 "0a2-10": dict(accent=JUE,
   hero="stacking cups and boxes into a little tower and knocking it down, laughing together",
   mat="light plastic cups, plastic containers and small light boxes",
   steps=["a parent and baby sitting with plastic cups between them",
          "hands stacking plastic cups into a small tower",
          "a baby knocking down a tower of plastic cups, laughing"]),
 "0a2-11": dict(accent=ART,
   hero="finger painting with colorful yogurt on a tray, messy hands and a big happy smile",
   mat="plain yogurt, small bowls of food coloring, thick paper and a tray, a big bib",
   steps=["a baby in front of a tray with bowls of colored yogurt",
          "a finger making a mark in colorful yogurt on a tray",
          "a baby smearing and mixing colored yogurt with both hands"]),
 "0a2-12": dict(accent=JUE,
   hero="putting objects into a box and taking them out again, delighted by the surprise",
   mat="a cardboard box, fabric balls, soft toys and rolled socks, a blanket",
   steps=["a baby sitting on a blanket with a box and soft toys",
          "small hands putting a soft ball into a box",
          "a baby taking soft toys back out of a box, delighted"]),

 # ---------------- 0 a 2 (nuevas 13-36) ----------------
 "0a2-13": dict(accent=SEN,
   hero="pressing and smearing colorful paint inside a sealed clear zip bag taped to a table, mess-free and fascinated",
   mat="a zip freezer bag, finger paint in two colors, strong tape",
   steps=["a sealed clear bag of colorful paint taped flat on a table",
          "a baby's finger pressing into a paint-filled sealed bag",
          "swirled blue and yellow paint mixing inside a sealed bag"]),
 "0a2-14": dict(accent=SEN,
   hero="walking barefoot along a path of different textured surfaces, holding a parent's hands",
   mat="a row of textured surfaces: a towel, a rug, bubble wrap, a sponge mat, felt, tape",
   steps=["different textured mats taped in a row on the floor",
          "a barefoot baby stepping onto a textured mat, parent holding hands",
          "tiny bare feet standing on bubble wrap"]),
 "0a2-15": dict(accent=SEN,
   hero="touching brightly colored ice cubes melting on a tray, surprised by the cold",
   mat="an ice cube tray, colored water, a rimmed tray, a towel",
   steps=["colorful ice cubes sitting on a tray",
          "a baby's hand touching a bright colored ice cube",
          "a melting colored ice cube leaving a trail of color on a tray"]),
 "0a2-16": dict(accent=SEN,
   hero="lying down looking at a high-contrast black and white pattern card held close by a parent",
   mat="white cards with bold black shapes: spirals, stripes, circles, a black marker",
   steps=["simple bold black and white pattern cards laid out",
          "a parent holding a black and white card near a lying baby",
          "a baby's eyes following a striped black and white card"]),
 "0a2-17": dict(accent=SEN,
   hero="squeezing and squishing balloons filled with different materials, exploring with both hands",
   mat="sturdy balloons filled with flour, rice and lentils, a small funnel",
   steps=["several balloons filled with different materials in a basket",
          "a baby's hands squeezing a soft filled balloon",
          "a parent's hands and a baby comparing two squishy balloons"]),
 "0a2-18": dict(accent=REC,
   hero="chasing and crawling after a soft ball rolling across the floor, joyful",
   mat="a soft lightweight fabric ball on a blanket",
   steps=["a parent rolling a soft ball toward a seated baby",
          "a baby pushing a soft ball back with both hands",
          "a baby crawling to reach a soft ball on the floor"]),
 "0a2-19": dict(accent=REC,
   hero="shaking homemade bottle shakers that rattle, smiling at the sound",
   mat="small plastic bottles filled with rice, pasta and beads, tape to seal the caps",
   steps=["clear bottles filled with colorful rice and beads, sealed",
          "a parent shaking a homemade bottle shaker",
          "a baby's hands shaking a rattling bottle shaker"]),
 "0a2-20": dict(accent=REC,
   hero="dancing and waving light flowing scarves in the air to music",
   mat="thin light scarves and flowing fabrics",
   steps=["a parent waving a light scarf in the air",
          "a light scarf floating slowly down to the floor",
          "a baby waving a colorful scarf with one hand"]),
 "0a2-21": dict(accent=REC,
   hero="blowing a light feather to make it float in the air, delighted",
   mat="a few large light feathers on a tray",
   steps=["large light feathers resting on a tray",
          "a parent blowing a feather into the air",
          "a baby blowing softly at a feather held near their mouth"]),
 "0a2-22": dict(accent=REC,
   hero="tapping a homemade drum made from a tin and a stretched balloon, rice bouncing on top",
   mat="a clean wide tin, a large balloon stretched over it, scissors and tape",
   steps=["a tin with a stretched balloon membrane taped as a drum",
          "a baby's hand patting the stretched balloon drum",
          "grains of rice bouncing on top of a tapped drum"]),
 "0a2-23": dict(accent=REC,
   hero="standing and pushing a weighted cardboard box forward like a walker, taking first steps",
   mat="a sturdy cardboard box weighted with books and bottles",
   steps=["a cardboard box weighted with a couple of books inside",
          "a baby standing and gripping the edge of a box",
          "a baby pushing a box forward across the floor, parent beside"]),
 "0a2-24": dict(accent=JUE,
   hero="lifting an opaque cup to find a hidden toy underneath, surprised and delighted",
   mat="two or three opaque cups and a small toy",
   steps=["a small toy sitting beside an upside-down opaque cup",
          "a hand covering a toy with an opaque cup",
          "a baby lifting a cup to reveal the hidden toy"]),
 "0a2-25": dict(accent=JUE,
   hero="dropping a ball into a cardboard tube and watching it roll out the other end",
   mat="a cardboard tube, small soft balls and large pom-poms, tape",
   steps=["a cardboard tube taped diagonally to a box",
          "a baby's hand dropping a ball into the top of a tube",
          "a ball rolling out the bottom of a tube into a bowl"]),
 "0a2-26": dict(accent=JUE,
   hero="pulling colorful fabric scarves out of a tissue box one after another, surprised",
   mat="an empty tissue box filled with knotted fabric scarves",
   steps=["a tissue box with a fabric scarf poking out of the slot",
          "a baby's hand pulling a scarf out of a tissue box",
          "a pile of colorful scarves pulled from a box"]),
 "0a2-27": dict(accent=JUE,
   hero="sorting big and small soft balls into two baskets, focused",
   mat="soft balls in two clearly different sizes, two baskets",
   steps=["big and small soft balls beside two baskets",
          "a baby's hand placing a big ball into a basket",
          "two baskets, one with big balls and one with small balls"]),
 "0a2-28": dict(accent=JUE,
   hero="tossing soft balls into a big box, laughing with each throw",
   mat="a big box or basket, soft balls, rolled socks and large pom-poms",
   steps=["a big box on the floor with soft balls beside it",
          "a baby's hand dropping a soft ball into a box",
          "a baby tossing a rolled sock toward a box"]),
 "0a2-29": dict(accent=EMO,
   hero="a parent and baby playing hand-gesture nursery rhymes face to face, laughing",
   mat="just warm open hands, no objects on a cozy rug",
   steps=["a parent's hands doing a finger nursery-rhyme gesture",
          "a baby sitting on a parent's lap watching their hands",
          "a parent guiding a baby's tiny hands to clap"]),
 "0a2-30": dict(accent=EMO,
   hero="a parent gently giving a baby a soothing massage on a soft blanket, calm and loving",
   mat="a soft towel, a small bottle of baby-safe oil, a cozy warm room",
   steps=["a parent warming oil between their hands",
          "a parent's hands gently stroking a baby's leg",
          "a calm baby lying relaxed on a soft blanket"]),
 "0a2-31": dict(accent=EMO,
   hero="a parent gently wrapping a baby in a soft blanket like a little burrito and rocking, cozy",
   mat="one soft light blanket",
   steps=["a baby lying on the edge of a soft blanket",
          "a parent gently wrapping a baby in a blanket, face free",
          "a parent rocking a swaddled baby, smiling"]),
 "0a2-32": dict(accent=EMO,
   hero="a parent gently touching and naming a baby's nose in a tickle game, both laughing",
   mat="just warm hands and a small mirror",
   steps=["a parent touching their own nose playfully",
          "a parent gently touching a baby's nose",
          "a parent tickling a baby's tummy, both laughing"]),
 "0a2-33": dict(accent=EMO,
   hero="a parent and baby sitting facing each other rolling a soft ball back and forth, taking turns",
   mat="a medium soft ball on the floor",
   steps=["a parent and baby sitting facing each other, legs open",
          "a soft ball rolling toward a baby's open hands",
          "a baby pushing a ball back toward a parent"]),
 "0a2-34": dict(accent=NAT,
   hero="a parent carrying a baby outdoors, both pausing to listen to birds and wind in a park",
   mat="a calm outdoor walk in a garden or park",
   steps=["a parent carrying a baby outdoors in a green park",
          "a parent and baby pausing to listen, a bird on a branch nearby",
          "a parent pointing up at leaves rustling in the wind"]),
 "0a2-35": dict(accent=NAT,
   hero="exploring a basket of large natural treasures like leaves, pine cones and smooth stones",
   mat="a basket with large leaves, pine cones, smooth stones and short twigs",
   steps=["a basket filled with large leaves, pine cones and smooth stones",
          "a baby's hand picking up a large leaf from a basket",
          "a baby holding a rough pine cone, exploring its texture"]),
 "0a2-36": dict(accent=ART,
   hero="painting with water and a big brush on an outdoor wall, marks appearing and drying away",
   mat="a thick brush and a small roller, a bucket with a little water, an outdoor wall",
   steps=["a bucket of water and a thick brush by an outdoor wall",
          "a baby's hand brushing water onto a wall, leaving a dark mark",
          "wet brush marks slowly drying and fading on a sunny wall"]),

 # ---------------- 3 a 5 (existentes 01-12) ----------------
 "3a5-01": dict(accent=EXP,
   hero="watching a homemade volcano erupt with colorful foam on a tray, amazed",
   mat="a small cup, baking soda, a glass of vinegar, food coloring, a deep tray",
   steps=["hands spooning baking soda into a small cup",
          "adding drops of red coloring onto baking soda in a cup",
          "colorful foam erupting and overflowing from a cup onto a tray"]),
 "3a5-02": dict(accent=EXP,
   hero="watching drops of food coloring swirl and spread across a plate of milk, fascinated",
   mat="a shallow plate, milk, drops of food coloring, dish soap, a cotton swab",
   steps=["dropping colored food dye onto a plate of milk",
          "colorful dye drops floating on the surface of milk",
          "a cotton swab touching milk as colors burst and swirl away"]),
 "3a5-03": dict(accent=SEN,
   hero="kneading and shaping soft homemade dough with their hands at a table",
   mat="flour, fine salt, warm water, a spoon of oil, food coloring, a big bowl",
   steps=["hands mixing flour and salt in a bowl",
          "kneading soft dough in a bowl while adding water",
          "shaping a ball of soft colored dough on a table"]),
 "3a5-04": dict(accent=SEN,
   hero="reaching a hand into a closed mystery box to guess a hidden object only by touch, curious",
   mat="a cardboard box with a hand hole, a spoon, sponge, ball, sock and clothes peg",
   steps=["a child's hand reaching into a hole in a mystery box",
          "fingers feeling a hidden object inside a box",
          "pulling a sponge out of a mystery box to check the guess"]),
 "3a5-05": dict(accent=REC,
   hero="jumping and balancing across an obstacle course built from cushions and blankets in the living room",
   mat="cushions and pillows, a blanket, two chairs, tape or rope",
   steps=["cushions laid out as stepping stones on the floor",
          "a blanket over two chairs forming a crawl tunnel",
          "a child balancing along a taped line on the floor"]),
 "3a5-06": dict(accent=REC,
   hero="rolling a soft ball to knock down a set of plastic bottles arranged like bowling pins",
   mat="six empty plastic bottles, a sock ball, a little sand, tape for the line",
   steps=["six plastic bottles set up like bowling pins in a triangle",
          "a child rolling a sock ball toward bottle pins",
          "plastic bottle pins knocked over by a sock ball"]),
 "3a5-07": dict(accent=JUE,
   hero="playing pretend shop with cardboard coins and little boxes of goods on a small counter",
   mat="home items as goods, cardboard coins and bills, a box counter, a shopping bag",
   steps=["goods arranged on a pretend shop counter with price tags",
          "cardboard coins being handed over at a pretend shop",
          "a child putting goods into a shopping bag at a play shop"]),
 "3a5-08": dict(accent=JUE,
   hero="running around the home collecting objects of every color into a rainbow basket",
   mat="colored paper cards, a basket, household objects of many colors",
   steps=["a child holding up a red color card",
          "searching the house and picking up a red object",
          "a basket filling with objects sorted by color"]),
 "3a5-09": dict(accent=EMO,
   hero="drawing simple round faces showing happy, angry and sad feelings on paper",
   mat="paper or paper plates, crayons, a mirror",
   steps=["drawing simple round faces with different feelings on paper",
          "a child pointing at a sad drawn face",
          "a child making an angry face in a mirror beside a drawing"]),
 "3a5-10": dict(accent=ART,
   hero="stamping colorful shapes onto paper using stamps cut from potatoes and vegetables",
   mat="a potato and carrot cut as stamps, paint, a plate, paper",
   steps=["dipping a potato stamp into paint on a plate",
          "pressing a potato stamp onto paper",
          "a sheet of paper covered with colorful printed stamps"]),
 "3a5-11": dict(accent=ART,
   hero="gluing leaves, petals and little twigs onto paper to make a nature collage",
   mat="leaves, flowers, twigs and seeds, cardboard, glue, crayons",
   steps=["leaves, flowers and twigs spread out on a table",
          "a child gluing a leaf onto cardboard",
          "a finished nature collage of leaves and petals"]),
 "3a5-12": dict(accent=NAT,
   hero="outdoors with a cardboard magnifying glass discovering little bugs in the garden",
   mat="a clear jar, a cardboard magnifying glass, paper and pencils",
   steps=["a child looking at the ground through a cardboard magnifying glass",
          "observing a ladybug on a leaf up close",
          "sketching a found bug on paper outdoors"]),

 # ---------------- 3 a 5 (nuevas 13-36) ----------------
 "3a5-13": dict(accent=EXP,
   hero="watching a homemade lava lamp with colorful bubbles rising and falling in a tall jar, amazed",
   mat="a tall clear jar, vegetable oil, water, food coloring, an effervescent tablet, a tray",
   steps=["pouring colored water into a jar with a layer of oil on top",
          "dropping a piece of effervescent tablet into a jar",
          "colorful bubbles rising and falling inside a tall jar"]),
 "3a5-14": dict(accent=EXP,
   hero="watching white flowers slowly turn blue and red as they drink colored water from glasses",
   mat="white carnation flowers or a celery stalk, glasses of water, food coloring",
   steps=["stirring food coloring into glasses of water",
          "placing a white flower stem into a glass of colored water",
          "white petals turning blue after drinking colored water"]),
 "3a5-15": dict(accent=EXP,
   hero="watching a balloon inflate by itself on top of a bottle as baking soda and vinegar foam, surprised",
   mat="a plastic bottle, vinegar, baking soda, a balloon, a funnel",
   steps=["filling a balloon with baking soda using a funnel",
          "fitting a balloon over the neck of a bottle of vinegar",
          "a balloon inflating by itself on a foaming bottle"]),
 "3a5-16": dict(accent=EXP,
   hero="testing which objects float or sink in a basin of water, like a little water detective",
   mat="a basin of water, a cork, a stone, a spoon, a sponge, a toy, a lid, a towel",
   steps=["holding an object over a basin, predicting float or sink",
          "an object dropped into water, floating on the surface",
          "objects sorted into floating and sinking groups by a basin"]),
 "3a5-17": dict(accent=SEN,
   hero="digging and pouring semolina on a tray, burying and finding little toys, absorbed",
   mat="a low tray, semolina or fine flour, spoons, cups, funnels and small toys",
   steps=["a tray of semolina with spoons and cups around it",
          "small hands digging and pouring semolina with a cup",
          "finding a small toy buried in semolina"]),
 "3a5-18": dict(accent=SEN,
   hero="painting puffy three-dimensional clouds with fluffy homemade puff paint, fascinated by the texture",
   mat="shaving foam, white glue, food coloring, thick cardboard, mixing spoons",
   steps=["mixing shaving foam and glue into fluffy colored paint",
          "spreading puffy paint onto cardboard with a spoon",
          "raised fluffy painted clouds drying on cardboard"]),
 "3a5-19": dict(accent=SEN,
   hero="shaking opaque jars and guessing what is hidden inside by the sound, curious",
   mat="identical opaque jars filled with rice, beans, coins, water and cotton, tape",
   steps=["a row of identical sealed opaque jars",
          "a child shaking a jar and listening closely",
          "opening a jar to reveal the rice hidden inside"]),
 "3a5-20": dict(accent=REC,
   hero="hopping on one foot across a chalk hopscotch grid numbered one to ten",
   mat="chalk for the ground or paper tape, a flat stone or beanbag",
   steps=["a numbered hopscotch grid drawn in chalk on the ground",
          "tossing a flat stone onto a hopscotch square",
          "a child hopping on one foot across hopscotch squares"]),
 "3a5-21": dict(accent=REC,
   hero="jumping from cushion to cushion pretending the floor is lava, excited",
   mat="cushions and pillows, newspaper sheets or cardboard pieces",
   steps=["cushions spread across the floor as safe islands",
          "a child jumping from one cushion to another",
          "a child balancing on a cushion island, arms out"]),
 "3a5-22": dict(accent=REC,
   hero="hopping forward inside a sack in a fun family sack race outdoors",
   mat="a pillowcase or sack per player, an open outdoor space",
   steps=["children stepping into sacks at a start line",
          "a child hopping forward inside a sack",
          "crossing a finish line while hopping in a sack"]),
 "3a5-23": dict(accent=REC,
   hero="dancing to music and freezing like a statue when it stops, laughing",
   mat="cheerful music, a device to pause it, open space",
   steps=["children dancing freely to music in a room",
          "everyone frozen mid-pose like statues",
          "a child frozen balancing on one foot, smiling"]),
 "3a5-24": dict(accent=JUE,
   hero="flipping handmade cards to find matching pairs in a memory game",
   mat="cardboard cards, markers or stickers for pictures, scissors",
   steps=["handmade picture cards laid face down in rows",
          "a child flipping over two cards to find a match",
          "two matching picture cards turned face up"]),
 "3a5-25": dict(accent=JUE,
   hero="rolling a giant homemade action dice that says jump, spin or clap, then acting it out",
   mat="a square cardboard box, paper and markers, tape",
   steps=["a large cardboard dice with action pictures on each face",
          "a child rolling a big cardboard action dice",
          "a child jumping while following the action on the dice"]),
 "3a5-26": dict(accent=JUE,
   hero="fishing paper fish with a magnet rod, focused and patient",
   mat="cardboard fish with paper clips, a stick rod, string, a magnet",
   steps=["paper fish with paper clips spread on the floor",
          "lowering a magnet rod toward a paper fish",
          "lifting a paper fish on a magnet rod into a bucket"]),
 "3a5-27": dict(accent=JUE,
   hero="playing picture bingo together, marking pictures with little tokens",
   mat="bingo cards with picture grids, tokens or beans, picture call cards",
   steps=["a picture bingo card with tokens beside it",
          "drawing a picture call card and naming it",
          "marking a matching picture on a bingo card with a token"]),
 "3a5-28": dict(accent=ART,
   hero="blowing drops of paint through a straw to make branching shapes, delighted",
   mat="watery tempera paint, a straw per person, thick paper, spoons",
   steps=["dropping watery paint onto paper with a spoon",
          "blowing a paint drop through a straw across paper",
          "branching blown-paint shapes spreading on paper"]),
 "3a5-29": dict(accent=ART,
   hero="building a picture from colorful paper circles, squares and triangles",
   mat="colored paper, round-tip scissors, glue, a base sheet",
   steps=["colorful paper geometric shapes cut and sorted",
          "gluing a paper triangle onto a base sheet",
          "a finished picture made of geometric paper shapes"]),
 "3a5-30": dict(accent=ART,
   hero="bringing a sock puppet character to life on one hand, playful",
   mat="a clean sock, buttons or felt for eyes, wool for hair, glue or thread",
   steps=["a clean sock with felt eyes laid out with craft supplies",
          "gluing button eyes onto a sock puppet",
          "a finished sock puppet talking on a hand"]),
 "3a5-31": dict(accent=ART,
   hero="filling a simple drawing with tiny colored paper pieces like a mosaic",
   mat="colored paper pieces sorted by color, a glue stick, a sheet with a simple outline",
   steps=["torn colored paper pieces sorted into little bowls",
          "gluing small paper pieces inside a drawn outline",
          "a finished paper mosaic filling a simple shape"]),
 "3a5-32": dict(accent=EMO,
   hero="moving an arrow on a homemade feelings thermometer to show how they feel",
   mat="cardboard, markers, a cardboard arrow with a brad fastener",
   steps=["a feelings thermometer with green, yellow and red zones",
          "a child moving the arrow on a feelings thermometer",
          "a parent and child breathing deeply together to calm down"]),
 "3a5-33": dict(accent=EMO,
   hero="adding a little note about a happy moment into a decorated jar",
   mat="a clear jar, colorful paper slips, a pencil",
   steps=["a decorated jar with colorful note slips beside it",
          "a hand writing a little note about something good",
          "folding a note and dropping it into a jar"]),
 "3a5-34": dict(accent=EMO,
   hero="giving voice to stuffed animals to talk about feelings, cozy",
   mat="stuffed animals or dolls, a comfy spot",
   steps=["a child holding two stuffed animals facing each other",
          "a stuffed animal seeming to talk to a child",
          "a child hugging a stuffed animal warmly"]),
 "3a5-35": dict(accent=NAT,
   hero="watching a bean sprout and grow on damp cotton inside a clear jar",
   mat="a clear jar or glass, cotton, a dry bean, water",
   steps=["placing a bean between cotton and the glass of a jar",
          "a bean sprouting a small root on damp cotton",
          "drawing the growing bean plant in a notebook"]),
 "3a5-36": dict(accent=NAT,
   hero="hanging a homemade bird feeder and watching birds come to eat",
   mat="a cardboard tube or bottle, peanut butter, birdseed, string",
   steps=["spreading peanut butter on a cardboard tube",
          "rolling a peanut-butter tube in birdseed",
          "hanging a seed-covered bird feeder on a branch"]),
}
