# -*- coding: utf-8 -*-
"""Prompts de imagen (en inglés, para evitar texto incrustado) de cada actividad.
PROMPTS[id] = {accent, hero, mat, steps[3]}. Lo consume scripts/gen_images.py.
'hero' es opcional para las actividades cuyo hero ya estaba generado.
"""
EXP, SEN, REC, JUE, EMO, ART, NAT = (
    "#3E6E94", "#7E57A6", "#E8744F", "#2E7D5B", "#D24D6E", "#F2A03D", "#5B9E4A")

PROMPTS = {
 # ---------------- 0 a 2 (existentes 01-12) ----------------
 "0a2-01": dict(accent=SEN,
   hero="exploring a woven basket filled with everyday wooden spoons, fabric scraps and natural objects; the baby reaches in with curiosity",
   mat="a low wicker basket, a wooden spoon, a sponge, a small metal cup, a fabric scrap, a soft fabric ball, a blanket",
   steps=["a baby sitting on a blanket with a treasure basket within reach",
          "a baby's hands lifting a wooden spoon out of a basket",
          "a parent's hand and a baby touching a shiny metal cup together"]),
 "0a2-02": dict(accent=SEN,
   hero="blowing soft soap bubbles that float and shimmer while the baby reaches up to touch them, delighted",
   mat="a bowl of warm soapy water and a bubble wand",
   steps=["a parent holding a baby comfortably on their lap",
          "a parent gently blowing soap bubbles into the air",
          "a baby reaching up to pop a floating soap bubble"]),
 "0a2-03": dict(accent=SEN,
   hero="gazing at a clear sensory bottle filled with water, glitter and floating shapes, calm and mesmerized, the parent holding it",
   mat="a small clear plastic bottle, water, colorful buttons, sequins and glitter, glue to seal the cap",
   steps=["a parent shaking a glitter sensory bottle gently",
          "a clear sensory bottle rolling slowly across the floor",
          "a baby's hands holding and turning a glitter bottle"]),
 "0a2-04": dict(accent=SEN,
   hero="splashing and pouring water between cups and small containers with a spoon, having fun",
   mat="a low basin with a little water, cups, mugs and spoons of different sizes, a towel",
   steps=["a baby sitting in front of a low basin of water",
          "small hands pouring water from a cup into a basin",
          "a baby splashing water between two small containers"]),
 "0a2-05": dict(accent=SEN,
   hero="touching a soft patchwork blanket made of many different fabric textures",
   mat="scraps of different fabrics, a base blanket, needle and thread",
   steps=["a baby lying on a soft patchwork texture blanket",
          "a parent guiding a baby's hand over fabric patches",
          "a baby's hand touching a fluffy fabric square"]),
 "0a2-06": dict(accent=EMO,
   hero="playing peekaboo, the parent hiding and reappearing behind their hands while the baby giggles",
   mat="a thin soft scarf",
   steps=["a parent hiding their face behind both hands",
          "a parent peeking out from behind a thin scarf, smiling",
          "a happy baby reaching toward a smiling parent"]),
 "0a2-07": dict(accent=EMO,
   hero="in front of a mirror making happy faces and discovering their own reflection together",
   mat="a safe unbreakable mirror",
   steps=["a parent holding a baby in front of a mirror",
          "a parent pointing at a baby's reflection in a mirror",
          "a parent making a happy face in a mirror with a baby"]),
 "0a2-08": dict(accent=REC,
   hero="making music with pots, wooden spoons and tins used as drums, joyful and lively",
   mat="pots and plastic containers, wooden spoons, a sealed jar with rice inside",
   steps=["a baby sitting among pots and wooden spoons on the floor",
          "small hands tapping a pot with a wooden spoon",
          "a baby shaking a homemade rice maraca jar"]),
 "0a2-09": dict(accent=REC,
   hero="crawling and climbing over a soft course of cushions and blankets, the parent encouraging",
   mat="cushions and pillows of different sizes, blankets, open cardboard boxes",
   steps=["a baby at the start of a soft cushion course, parent encouraging",
          "a baby climbing over a big soft cushion",
          "a baby crawling under a blanket tunnel"]),
 "0a2-10": dict(accent=JUE,
   hero="stacking cups and boxes into a little tower and knocking it down, laughing together",
   mat="light plastic cups, plastic containers and small light boxes",
   steps=["a parent and baby sitting with plastic cups between them",
          "hands stacking plastic cups into a small tower",
          "a baby knocking down a tower of plastic cups, laughing"]),
 "0a2-11": dict(accent=ART,
   hero="finger painting with colorful yogurt on a tray, messy hands and a big happy smile",
   mat="plain yogurt, small bowls of food coloring, thick paper and a tray, a big bib",
   steps=["a baby in front of a tray with bowls of colored yogurt",
          "a finger making a mark in colorful yogurt on a tray",
          "a baby smearing and mixing colored yogurt with both hands"]),
 "0a2-12": dict(accent=JUE,
   hero="putting objects into a box and taking them out again, delighted by the surprise",
   mat="a cardboard box, fabric balls, soft toys and rolled socks, a blanket",
   steps=["a baby sitting on a blanket with a box and soft toys",
          "small hands putting a soft ball into a box",
          "a baby taking soft toys back out of a box, delighted"]),

 # ---------------- 0 a 2 (nuevas 13-36) ----------------
 "0a2-13": dict(accent=SEN,
   hero="pressing and smearing colorful paint inside a sealed clear zip bag taped to a table, mess-free and fascinated",
   mat="a zip freezer bag, finger paint in two colors, strong tape",
   steps=["a sealed clear bag of colorful paint taped flat on a table",
          "a baby's finger pressing into a paint-filled sealed bag",
          "swirled blue and yellow paint mixing inside a sealed bag"]),
 "0a2-14": dict(accent=SEN,
   hero="walking barefoot along a path of different textured surfaces, holding a parent's hands",
   mat="a row of textured surfaces: a towel, a rug, bubble wrap, a sponge mat, felt, tape",
   steps=["different textured mats taped in a row on the floor",
          "a barefoot baby stepping onto a textured mat, parent holding hands",
          "tiny bare feet standing on bubble wrap"]),
 "0a2-15": dict(accent=SEN,
   hero="touching brightly colored ice cubes melting on a tray, surprised by the cold",
   mat="an ice cube tray, colored water, a rimmed tray, a towel",
   steps=["colorful ice cubes sitting on a tray",
          "a baby's hand touching a bright colored ice cube",
          "a melting colored ice cube leaving a trail of color on a tray"]),
 "0a2-16": dict(accent=SEN,
   hero="lying down looking at a high-contrast black and white pattern card held close by a parent",
   mat="white cards with bold black shapes: spirals, stripes, circles, a black marker",
   steps=["simple bold black and white pattern cards laid out",
          "a parent holding a black and white card near a lying baby",
          "a baby's eyes following a striped black and white card"]),
 "0a2-17": dict(accent=SEN,
   hero="squeezing and squishing balloons filled with different materials, exploring with both hands",
   mat="sturdy balloons filled with flour, rice and lentils, a small funnel",
   steps=["several balloons filled with different materials in a basket",
          "a baby's hands squeezing a soft filled balloon",
          "a parent's hands and a baby comparing two squishy balloons"]),
 "0a2-18": dict(accent=REC,
   hero="chasing and crawling after a soft ball rolling across the floor, joyful",
   mat="a soft lightweight fabric ball on a blanket",
   steps=["a parent rolling a soft ball toward a seated baby",
          "a baby pushing a soft ball back with both hands",
          "a baby crawling to reach a soft ball on the floor"]),
 "0a2-19": dict(accent=REC,
   hero="shaking homemade bottle shakers that rattle, smiling at the sound",
   mat="small plastic bottles filled with rice, pasta and beads, tape to seal the caps",
   steps=["clear bottles filled with colorful rice and beads, sealed",
          "a parent shaking a homemade bottle shaker",
          "a baby's hands shaking a rattling bottle shaker"]),
 "0a2-20": dict(accent=REC,
   hero="dancing and waving light flowing scarves in the air to music",
   mat="thin light scarves and flowing fabrics",
   steps=["a parent waving a light scarf in the air",
          "a light scarf floating slowly down to the floor",
          "a baby waving a colorful scarf with one hand"]),
 "0a2-21": dict(accent=REC,
   hero="blowing a light feather to make it float in the air, delighted",
   mat="a few large light feathers on a tray",
   steps=["large light feathers resting on a tray",
          "a parent blowing a feather into the air",
          "a baby blowing softly at a feather held near their mouth"]),
 "0a2-22": dict(accent=REC,
   hero="tapping a homemade drum made from a tin and a stretched balloon, rice bouncing on top",
   mat="a clean wide tin, a large balloon stretched over it, scissors and tape",
   steps=["a tin with a stretched balloon membrane taped as a drum",
          "a baby's hand patting the stretched balloon drum",
          "grains of rice bouncing on top of a tapped drum"]),
 "0a2-23": dict(accent=REC,
   hero="standing and pushing a weighted cardboard box forward like a walker, taking first steps",
   mat="a sturdy cardboard box weighted with books and bottles",
   steps=["a cardboard box weighted with a couple of books inside",
          "a baby standing and gripping the edge of a box",
          "a baby pushing a box forward across the floor, parent beside"]),
 "0a2-24": dict(accent=JUE,
   hero="lifting an opaque cup to find a hidden toy underneath, surprised and delighted",
   mat="two or three opaque cups and a small toy",
   steps=["a small toy sitting beside an upside-down opaque cup",
          "a hand covering a toy with an opaque cup",
          "a baby lifting a cup to reveal the hidden toy"]),
 "0a2-25": dict(accent=JUE,
   hero="dropping a ball into a cardboard tube and watching it roll out the other end",
   mat="a cardboard tube, small soft balls and large pom-poms, tape",
   steps=["a cardboard tube taped diagonally to a box",
          "a baby's hand dropping a ball into the top of a tube",
          "a ball rolling out the bottom of a tube into a bowl"]),
 "0a2-26": dict(accent=JUE,
   hero="pulling colorful fabric scarves out of a tissue box one after another, surprised",
   mat="an empty tissue box filled with knotted fabric scarves",
   steps=["a tissue box with a fabric scarf poking out of the slot",
          "a baby's hand pulling a scarf out of a tissue box",
          "a pile of colorful scarves pulled from a box"]),
 "0a2-27": dict(accent=JUE,
   hero="sorting big and small soft balls into two baskets, focused",
   mat="soft balls in two clearly different sizes, two baskets",
   steps=["big and small soft balls beside two baskets",
          "a baby's hand placing a big ball into a basket",
          "two baskets, one with big balls and one with small balls"]),
 "0a2-28": dict(accent=JUE,
   hero="tossing soft balls into a big box, laughing with each throw",
   mat="a big box or basket, soft balls, rolled socks and large pom-poms",
   steps=["a big box on the floor with soft balls beside it",
          "a baby's hand dropping a soft ball into a box",
          "a baby tossing a rolled sock toward a box"]),
 "0a2-29": dict(accent=EMO,
   hero="a parent and baby playing hand-gesture nursery rhymes face to face, laughing",
   mat="just warm open hands, no objects on a cozy rug",
   steps=["a parent's hands doing a finger nursery-rhyme gesture",
          "a baby sitting on a parent's lap watching their hands",
          "a parent guiding a baby's tiny hands to clap"]),
 "0a2-30": dict(accent=EMO,
   hero="a parent gently giving a baby a soothing massage on a soft blanket, calm and loving",
   mat="a soft towel, a small bottle of baby-safe oil, a cozy warm room",
   steps=["a parent warming oil between their hands",
          "a parent's hands gently stroking a baby's leg",
          "a calm baby lying relaxed on a soft blanket"]),
 "0a2-31": dict(accent=EMO,
   hero="a parent gently wrapping a baby in a soft blanket like a little burrito and rocking, cozy",
   mat="one soft light blanket",
   steps=["a baby lying on the edge of a soft blanket",
          "a parent gently wrapping a baby in a blanket, face free",
          "a parent rocking a swaddled baby, smiling"]),
 "0a2-32": dict(accent=EMO,
   hero="a parent gently touching and naming a baby's nose in a tickle game, both laughing",
   mat="just warm hands and a small mirror",
   steps=["a parent touching their own nose playfully",
          "a parent gently touching a baby's nose",
          "a parent tickling a baby's tummy, both laughing"]),
 "0a2-33": dict(accent=EMO,
   hero="a parent and baby sitting facing each other rolling a soft ball back and forth, taking turns",
   mat="a medium soft ball on the floor",
   steps=["a parent and baby sitting facing each other, legs open",
          "a soft ball rolling toward a baby's open hands",
          "a baby pushing a ball back toward a parent"]),
 "0a2-34": dict(accent=NAT,
   hero="a parent carrying a baby outdoors, both pausing to listen to birds and wind in a park",
   mat="a calm outdoor walk in a garden or park",
   steps=["a parent carrying a baby outdoors in a green park",
          "a parent and baby pausing to listen, a bird on a branch nearby",
          "a parent pointing up at leaves rustling in the wind"]),
 "0a2-35": dict(accent=NAT,
   hero="exploring a basket of large natural treasures like leaves, pine cones and smooth stones",
   mat="a basket with large leaves, pine cones, smooth stones and short twigs",
   steps=["a basket filled with large leaves, pine cones and smooth stones",
          "a baby's hand picking up a large leaf from a basket",
          "a baby holding a rough pine cone, exploring its texture"]),
 "0a2-36": dict(accent=ART,
   hero="painting with water and a big brush on an outdoor wall, marks appearing and drying away",
   mat="a thick brush and a small roller, a bucket with a little water, an outdoor wall",
   steps=["a bucket of water and a thick brush by an outdoor wall",
          "a baby's hand brushing water onto a wall, leaving a dark mark",
          "wet brush marks slowly drying and fading on a sunny wall"]),

 # ---------------- 3 a 5 (existentes 01-12) ----------------
 "3a5-01": dict(accent=EXP,
   hero="watching a homemade volcano erupt with colorful foam on a tray, amazed",
   mat="a small cup, baking soda, a glass of vinegar, food coloring, a deep tray",
   steps=["hands spooning baking soda into a small cup",
          "adding drops of red coloring onto baking soda in a cup",
          "colorful foam erupting and overflowing from a cup onto a tray"]),
 "3a5-02": dict(accent=EXP,
   hero="watching drops of food coloring swirl and spread across a plate of milk, fascinated",
   mat="a shallow plate, milk, drops of food coloring, dish soap, a cotton swab",
   steps=["dropping colored food dye onto a plate of milk",
          "colorful dye drops floating on the surface of milk",
          "a cotton swab touching milk as colors burst and swirl away"]),
 "3a5-03": dict(accent=SEN,
   hero="kneading and shaping soft homemade dough with their hands at a table",
   mat="flour, fine salt, warm water, a spoon of oil, food coloring, a big bowl",
   steps=["hands mixing flour and salt in a bowl",
          "kneading soft dough in a bowl while adding water",
          "shaping a ball of soft colored dough on a table"]),
 "3a5-04": dict(accent=SEN,
   hero="reaching a hand into a closed mystery box to guess a hidden object only by touch, curious",
   mat="a cardboard box with a hand hole, a spoon, sponge, ball, sock and clothes peg",
   steps=["a child's hand reaching into a hole in a mystery box",
          "fingers feeling a hidden object inside a box",
          "pulling a sponge out of a mystery box to check the guess"]),
 "3a5-05": dict(accent=REC,
   hero="jumping and balancing across an obstacle course built from cushions and blankets in the living room",
   mat="cushions and pillows, a blanket, two chairs, tape or rope",
   steps=["cushions laid out as stepping stones on the floor",
          "a blanket over two chairs forming a crawl tunnel",
          "a child balancing along a taped line on the floor"]),
 "3a5-06": dict(accent=REC,
   hero="rolling a soft ball to knock down a set of plastic bottles arranged like bowling pins",
   mat="six empty plastic bottles, a sock ball, a little sand, tape for the line",
   steps=["six plastic bottles set up like bowling pins in a triangle",
          "a child rolling a sock ball toward bottle pins",
          "plastic bottle pins knocked over by a sock ball"]),
 "3a5-07": dict(accent=JUE,
   hero="playing pretend shop with cardboard coins and little boxes of goods on a small counter",
   mat="home items as goods, cardboard coins and bills, a box counter, a shopping bag",
   steps=["goods arranged on a pretend shop counter with price tags",
          "cardboard coins being handed over at a pretend shop",
          "a child putting goods into a shopping bag at a play shop"]),
 "3a5-08": dict(accent=JUE,
   hero="running around the home collecting objects of every color into a rainbow basket",
   mat="colored paper cards, a basket, household objects of many colors",
   steps=["a child holding up a red color card",
          "searching the house and picking up a red object",
          "a basket filling with objects sorted by color"]),
 "3a5-09": dict(accent=EMO,
   hero="drawing simple round faces showing happy, angry and sad feelings on paper",
   mat="paper or paper plates, crayons, a mirror",
   steps=["drawing simple round faces with different feelings on paper",
          "a child pointing at a sad drawn face",
          "a child making an angry face in a mirror beside a drawing"]),
 "3a5-10": dict(accent=ART,
   hero="stamping colorful shapes onto paper using stamps cut from potatoes and vegetables",
   mat="a potato and carrot cut as stamps, paint, a plate, paper",
   steps=["dipping a potato stamp into paint on a plate",
          "pressing a potato stamp onto paper",
          "a sheet of paper covered with colorful printed stamps"]),
 "3a5-11": dict(accent=ART,
   hero="gluing leaves, petals and little twigs onto paper to make a nature collage",
   mat="leaves, flowers, twigs and seeds, cardboard, glue, crayons",
   steps=["leaves, flowers and twigs spread out on a table",
          "a child gluing a leaf onto cardboard",
          "a finished nature collage of leaves and petals"]),
 "3a5-12": dict(accent=NAT,
   hero="outdoors with a cardboard magnifying glass discovering little bugs in the garden",
   mat="a clear jar, a cardboard magnifying glass, paper and pencils",
   steps=["a child looking at the ground through a cardboard magnifying glass",
          "observing a ladybug on a leaf up close",
          "sketching a found bug on paper outdoors"]),

 # ---------------- 3 a 5 (nuevas 13-36) ----------------
 "3a5-13": dict(accent=EXP,
   hero="watching a homemade lava lamp with colorful bubbles rising and falling in a tall jar, amazed",
   mat="a tall clear jar, vegetable oil, water, food coloring, an effervescent tablet, a tray",
   steps=["pouring colored water into a jar with a layer of oil on top",
          "dropping a piece of effervescent tablet into a jar",
          "colorful bubbles rising and falling inside a tall jar"]),
 "3a5-14": dict(accent=EXP,
   hero="watching white flowers slowly turn blue and red as they drink colored water from glasses",
   mat="white carnation flowers or a celery stalk, glasses of water, food coloring",
   steps=["stirring food coloring into glasses of water",
          "placing a white flower stem into a glass of colored water",
          "white petals turning blue after drinking colored water"]),
 "3a5-15": dict(accent=EXP,
   hero="watching a balloon inflate by itself on top of a bottle as baking soda and vinegar foam, surprised",
   mat="a plastic bottle, vinegar, baking soda, a balloon, a funnel",
   steps=["filling a balloon with baking soda using a funnel",
          "fitting a balloon over the neck of a bottle of vinegar",
          "a balloon inflating by itself on a foaming bottle"]),
 "3a5-16": dict(accent=EXP,
   hero="testing which objects float or sink in a basin of water, like a little water detective",
   mat="a basin of water, a cork, a stone, a spoon, a sponge, a toy, a lid, a towel",
   steps=["holding an object over a basin, predicting float or sink",
          "an object dropped into water, floating on the surface",
          "objects sorted into floating and sinking groups by a basin"]),
 "3a5-17": dict(accent=SEN,
   hero="digging and pouring semolina on a tray, burying and finding little toys, absorbed",
   mat="a low tray, semolina or fine flour, spoons, cups, funnels and small toys",
   steps=["a tray of semolina with spoons and cups around it",
          "small hands digging and pouring semolina with a cup",
          "finding a small toy buried in semolina"]),
 "3a5-18": dict(accent=SEN,
   hero="painting puffy three-dimensional clouds with fluffy homemade puff paint, fascinated by the texture",
   mat="shaving foam, white glue, food coloring, thick cardboard, mixing spoons",
   steps=["mixing shaving foam and glue into fluffy colored paint",
          "spreading puffy paint onto cardboard with a spoon",
          "raised fluffy painted clouds drying on cardboard"]),
 "3a5-19": dict(accent=SEN,
   hero="shaking opaque jars and guessing what is hidden inside by the sound, curious",
   mat="identical opaque jars filled with rice, beans, coins, water and cotton, tape",
   steps=["a row of identical sealed opaque jars",
          "a child shaking a jar and listening closely",
          "opening a jar to reveal the rice hidden inside"]),
 "3a5-20": dict(accent=REC,
   hero="hopping on one foot across a chalk hopscotch grid numbered one to ten",
   mat="chalk for the ground or paper tape, a flat stone or beanbag",
   steps=["a numbered hopscotch grid drawn in chalk on the ground",
          "tossing a flat stone onto a hopscotch square",
          "a child hopping on one foot across hopscotch squares"]),
 "3a5-21": dict(accent=REC,
   hero="jumping from cushion to cushion pretending the floor is lava, excited",
   mat="cushions and pillows, newspaper sheets or cardboard pieces",
   steps=["cushions spread across the floor as safe islands",
          "a child jumping from one cushion to another",
          "a child balancing on a cushion island, arms out"]),
 "3a5-22": dict(accent=REC,
   hero="hopping forward inside a sack in a fun family sack race outdoors",
   mat="a pillowcase or sack per player, an open outdoor space",
   steps=["children stepping into sacks at a start line",
          "a child hopping forward inside a sack",
          "crossing a finish line while hopping in a sack"]),
 "3a5-23": dict(accent=REC,
   hero="dancing to music and freezing like a statue when it stops, laughing",
   mat="cheerful music, a device to pause it, open space",
   steps=["children dancing freely to music in a room",
          "everyone frozen mid-pose like statues",
          "a child frozen balancing on one foot, smiling"]),
 "3a5-24": dict(accent=JUE,
   hero="flipping handmade cards to find matching pairs in a memory game",
   mat="cardboard cards, markers or stickers for pictures, scissors",
   steps=["handmade picture cards laid face down in rows",
          "a child flipping over two cards to find a match",
          "two matching picture cards turned face up"]),
 "3a5-25": dict(accent=JUE,
   hero="rolling a giant homemade action dice that says jump, spin or clap, then acting it out",
   mat="a square cardboard box, paper and markers, tape",
   steps=["a large cardboard dice with action pictures on each face",
          "a child rolling a big cardboard action dice",
          "a child jumping while following the action on the dice"]),
 "3a5-26": dict(accent=JUE,
   hero="fishing paper fish with a magnet rod, focused and patient",
   mat="cardboard fish with paper clips, a stick rod, string, a magnet",
   steps=["paper fish with paper clips spread on the floor",
          "lowering a magnet rod toward a paper fish",
          "lifting a paper fish on a magnet rod into a bucket"]),
 "3a5-27": dict(accent=JUE,
   hero="playing picture bingo together, marking pictures with little tokens",
   mat="bingo cards with picture grids, tokens or beans, picture call cards",
   steps=["a picture bingo card with tokens beside it",
          "drawing a picture call card and naming it",
          "marking a matching picture on a bingo card with a token"]),
 "3a5-28": dict(accent=ART,
   hero="blowing drops of paint through a straw to make branching shapes, delighted",
   mat="watery tempera paint, a straw per person, thick paper, spoons",
   steps=["dropping watery paint onto paper with a spoon",
          "blowing a paint drop through a straw across paper",
          "branching blown-paint shapes spreading on paper"]),
 "3a5-29": dict(accent=ART,
   hero="building a picture from colorful paper circles, squares and triangles",
   mat="colored paper, round-tip scissors, glue, a base sheet",
   steps=["colorful paper geometric shapes cut and sorted",
          "gluing a paper triangle onto a base sheet",
          "a finished picture made of geometric paper shapes"]),
 "3a5-30": dict(accent=ART,
   hero="bringing a sock puppet character to life on one hand, playful",
   mat="a clean sock, buttons or felt for eyes, wool for hair, glue or thread",
   steps=["a clean sock with felt eyes laid out with craft supplies",
          "gluing button eyes onto a sock puppet",
          "a finished sock puppet talking on a hand"]),
 "3a5-31": dict(accent=ART,
   hero="filling a simple drawing with tiny colored paper pieces like a mosaic",
   mat="colored paper pieces sorted by color, a glue stick, a sheet with a simple outline",
   steps=["torn colored paper pieces sorted into little bowls",
          "gluing small paper pieces inside a drawn outline",
          "a finished paper mosaic filling a simple shape"]),
 "3a5-32": dict(accent=EMO,
   hero="moving an arrow on a homemade feelings thermometer to show how they feel",
   mat="cardboard, markers, a cardboard arrow with a brad fastener",
   steps=["a feelings thermometer with green, yellow and red zones",
          "a child moving the arrow on a feelings thermometer",
          "a parent and child breathing deeply together to calm down"]),
 "3a5-33": dict(accent=EMO,
   hero="adding a little note about a happy moment into a decorated jar",
   mat="a clear jar, colorful paper slips, a pencil",
   steps=["a decorated jar with colorful note slips beside it",
          "a hand writing a little note about something good",
          "folding a note and dropping it into a jar"]),
 "3a5-34": dict(accent=EMO,
   hero="giving voice to stuffed animals to talk about feelings, cozy",
   mat="stuffed animals or dolls, a comfy spot",
   steps=["a child holding two stuffed animals facing each other",
          "a stuffed animal seeming to talk to a child",
          "a child hugging a stuffed animal warmly"]),
 "3a5-35": dict(accent=NAT,
   hero="watching a bean sprout and grow on damp cotton inside a clear jar",
   mat="a clear jar or glass, cotton, a dry bean, water",
   steps=["placing a bean between cotton and the glass of a jar",
          "a bean sprouting a small root on damp cotton",
          "drawing the growing bean plant in a notebook"]),
 "3a5-36": dict(accent=NAT,
   hero="hanging a homemade bird feeder and watching birds come to eat",
   mat="a cardboard tube or bottle, peanut butter, birdseed, string",
   steps=["spreading peanut butter on a cardboard tube",
          "rolling a peanut-butter tube in birdseed",
          "hanging a seed-covered bird feeder on a branch"]),

 # ---------------- 6 a 8 (existentes 01-12) ----------------
 "6a8-01": dict(accent=EXP,
   hero="stacking honey, water and oil in colored layers inside a clear glass and watching them separate, amazed",
   mat="a tall clear glass, honey, water, cooking oil, food coloring, a spoon",
   steps=["pouring honey slowly into the bottom of a glass",
          "letting water slide down a spoon to layer it in a glass",
          "colored liquid layers stacked in a clear glass"]),
 "6a8-02": dict(accent=EXP,
   hero="launching a balloon rocket sliding along a long string across the room, excited",
   mat="a long balloon, a long string, a paper straw, tape, a clothes peg",
   steps=["threading a long string through a paper straw",
          "taping an inflated balloon to a straw on a string",
          "a balloon rocket zooming along a string across a room"]),
 "6a8-03": dict(accent=ART,
   hero="making a small colorful salt mandala, coloring salt with chalk in little bowls",
   mat="table salt, colored chalk, small cups, cardboard, liquid glue, a pencil",
   steps=["rubbing colored chalk into salt in a cup",
          "drawing glue lines on cardboard in a mandala pattern",
          "sprinkling colored salt over a glued mandala design"]),
 "6a8-04": dict(accent=SEN,
   hero="reaching into a closed mystery box to guess a hidden object by touch",
   mat="a cardboard box with a hand hole, an old sock cover, a sponge, a pine cone, a spoon",
   steps=["a hand reaching into a mystery box hole",
          "fingers feeling a hidden textured object inside a box",
          "pulling a pine cone out of a mystery box"]),
 "6a8-05": dict(accent=REC,
   hero="moving through a homemade obstacle course of jumps, tunnels and balance beams indoors",
   mat="cushions, chairs, a blanket, string, plastic cups, a stopwatch",
   steps=["a hand drawing an obstacle course plan on paper",
          "a blanket over two chairs forming a crawl tunnel",
          "a child balancing along a taped line, arms out"]),
 "6a8-06": dict(accent=REC,
   hero="bowling with plastic bottles as pins, rolling a ball to knock them all down",
   mat="plastic bottles, a little water or sand for weight, a ball or sock ball, paint",
   steps=["plastic bottles set up in a triangle like bowling pins",
          "a child rolling a ball toward bottle pins",
          "bottle pins knocked over by a rolling ball"]),
 "6a8-07": dict(accent=JUE,
   hero="drawing their own board game with a winding path on cardboard, with dice and tokens",
   mat="cardboard, markers, a dice, tokens like buttons and coins",
   steps=["drawing a winding path of squares on cardboard",
          "coloring special squares on a homemade board game",
          "writing challenge cards for a board game"]),
 "6a8-08": dict(accent=JUE,
   hero="following a trail of clue cards around the house to find a hidden treasure box",
   mat="paper and pencil for clues, a box for the treasure, a small prize, tape",
   steps=["writing a riddle clue on paper",
          "a child reading a clue card, thinking",
          "finding a treasure box with a small prize"]),
 "6a8-09": dict(accent=EMO,
   hero="holding a calm-down glitter jar and watching the glitter swirl slowly, peaceful",
   mat="a clear jar, warm water, clear glitter glue, fine glitter, food coloring",
   steps=["pouring glitter glue into a jar of warm water",
          "adding glitter and a drop of color to a jar",
          "glitter settling slowly in a calm-down jar"]),
 "6a8-10": dict(accent=ART,
   hero="performing a puppet show with handmade cardboard puppets behind a little stage",
   mat="cardboard, round-tip scissors, wooden sticks, paint pots, tape",
   steps=["drawing a character outline on cardboard",
          "painting a colorful cardboard puppet figure",
          "taping a stick to the back of a cardboard puppet"]),
 "6a8-11": dict(accent=NAT,
   hero="outdoors with a magnifying glass and a notebook exploring nature and sketching findings",
   mat="a notebook, colored pencils, a magnifying glass, a small bag, tape",
   steps=["a child observing leaves with a magnifying glass outdoors",
          "sketching a leaf and a bug in a notebook",
          "taping a found leaf into a nature notebook"]),
 "6a8-12": dict(accent=EXP,
   hero="rubbing a balloon on their hair and using static to lift small paper bits, surprised",
   mat="an inflated balloon, tiny paper bits, a thin thread, an empty soda can",
   steps=["rubbing a balloon on hair to charge it with static",
          "tiny paper bits jumping up toward a balloon",
          "a charged balloon bending a thin stream of water"]),

 # ---------------- 6 a 8 (nuevas 13-36) ----------------
 "6a8-13": dict(accent=EXP,
   hero="growing salt crystals on a string in a jar and watching them form like tiny jewels",
   mat="a glass jar, plenty of salt, a string tied to a pencil, hot water",
   steps=["stirring salt into a jar of warm water",
          "a string hanging from a pencil into a jar of salt water",
          "white salt crystals forming along a string in a jar"]),
 "6a8-14": dict(accent=EXP,
   hero="stretching and squishing homemade glittery slime, fascinated by the gooey texture",
   mat="white glue, baking soda, contact lens solution, glitter and food coloring, a bowl",
   steps=["pouring white glue and color into a bowl",
          "stirring slime as it pulls away from a bowl",
          "stretching stretchy glittery slime between two hands"]),
 "6a8-15": dict(accent=EXP,
   hero="watching an egg float in salty water but sink in plain water, surprised",
   mat="two tall glasses, water, plenty of salt, an egg, a spoon",
   steps=["an egg sinking to the bottom of a glass of water",
          "stirring lots of salt into a glass of water",
          "an egg floating in a glass of salty water"]),
 "6a8-16": dict(accent=EXP,
   hero="spying over the furniture through a homemade cardboard periscope, like a submarine",
   mat="a long cardboard box or milk carton, two small mirrors, scissors, tape, a ruler",
   steps=["a long cardboard tube with openings cut at top and bottom",
          "a small mirror taped at an angle inside a tube",
          "a child looking through a cardboard periscope over a sofa"]),
 "6a8-17": dict(accent=EXP,
   hero="watching a floating magnetized needle settle pointing north, like a homemade compass",
   mat="a sewing needle, a magnet, a piece of cork, a bowl of water",
   steps=["stroking a needle with a magnet in one direction",
          "a needle pushed through a small piece of cork",
          "a needle on cork floating in water, pointing north"]),
 "6a8-18": dict(accent=REC,
   hero="twisting into funny poses with hands and feet on colored circles, laughing",
   mat="an old sheet, paint or colored paper circles, a color spinner",
   steps=["rows of colored circles painted on a sheet on the floor",
          "spinning a homemade color and body-part spinner",
          "children twisted into tangled poses on colored circles"]),
 "6a8-19": dict(accent=REC,
   hero="playing slow balloon badminton with cardboard rackets indoors",
   mat="cardboard or plates, ice-cream sticks, a balloon, tape",
   steps=["making a cardboard racket with a stick handle",
          "hitting a balloon over a string with a cardboard racket",
          "two children rallying a balloon back and forth"]),
 "6a8-20": dict(accent=REC,
   hero="tossing beanbags into boxes for points, aiming carefully",
   mat="boxes of different sizes, fabric beanbags or rolled socks, number cards",
   steps=["boxes set at different distances with point numbers",
          "a child tossing a beanbag toward a box",
          "beanbags landing inside scoring boxes"]),
 "6a8-21": dict(accent=REC,
   hero="folding and flying paper airplanes to see which one flies farthest",
   mat="sheets of paper, a measuring tape, a pencil to note results",
   steps=["folding a paper airplane on a table",
          "throwing a paper airplane down a hallway",
          "measuring how far a paper airplane flew"]),
 "6a8-22": dict(accent=JUE,
   hero="playing giant tic-tac-toe with handmade tokens",
   mat="cardboard or tape for the board, bottle caps and stones as two token sets",
   steps=["a large three-by-three grid taped on the floor",
          "placing a token on a tic-tac-toe grid",
          "three matching tokens in a row winning the game"]),
 "6a8-23": dict(accent=JUE,
   hero="playing paper battleship, calling coordinates to find the hidden fleet",
   mat="grid paper, pencils, a folder to hide the boards",
   steps=["drawing ships on a secret grid",
          "calling out a coordinate to attack a grid",
          "marking hits and misses on a battleship grid"]),
 "6a8-24": dict(accent=JUE,
   hero="chaining handmade domino tiles in a family game",
   mat="firm cardboard tiles, a ruler, markers, scissors",
   steps=["drawing dots on handmade cardboard domino tiles",
          "matching domino tiles end to end on a table",
          "a long chain of domino tiles being built"]),
 "6a8-25": dict(accent=JUE,
   hero="acting out a word in silence while others guess, laughing",
   mat="slips of paper with words or pictures, a bowl, a timer",
   steps=["drawing a folded slip of paper from a bowl",
          "a child acting out a word with gestures, not talking",
          "others guessing as a child mimes an action"]),
 "6a8-26": dict(accent=ART,
   hero="weaving a dreamcatcher with yarn and feathers to hang over the bed",
   mat="a hoop from a paper plate, yarn, beads, feathers, ribbons, glue",
   steps=["wrapping yarn across a hoop in a web pattern",
          "threading a bead onto a dreamcatcher web",
          "feathers hanging from a finished dreamcatcher"]),
 "6a8-27": dict(accent=ART,
   hero="painting with watercolor and sprinkling salt to make magical sparkly textures",
   mat="watercolor paint, thick paper, coarse salt, brushes and water",
   steps=["painting wet watercolor washes on thick paper",
          "sprinkling coarse salt over wet watercolor",
          "starry salt textures revealed on dried watercolor"]),
 "6a8-28": dict(accent=ART,
   hero="folding paper into a dog, frog or bird, delighted as the animal appears",
   mat="square sheets of paper, markers for the details",
   steps=["folding a square sheet of paper in half",
          "creasing folds to shape an origami animal",
          "a finished origami animal with drawn eyes"]),
 "6a8-29": dict(accent=ART,
   hero="turning smooth stones into ladybugs and little monsters with paint",
   mat="smooth clean stones, paint, fine brushes, clear varnish",
   steps=["smooth stones beside paint pots and brushes",
          "painting a base color on a smooth stone",
          "adding fine details to a painted ladybug stone"]),
 "6a8-30": dict(accent=EMO,
   hero="writing three good things of the day in a decorated gratitude notebook",
   mat="a notebook, colored pencils, stickers",
   steps=["decorating the cover of a gratitude notebook",
          "writing three good things in a notebook",
          "reading earlier gratitude pages together"]),
 "6a8-31": dict(accent=EMO,
   hero="posting a loving note into a decorated family mailbox",
   mat="a cardboard box with a slot, paper and pencils, decorations",
   steps=["decorating a cardboard box as a family mailbox",
          "writing a kind note for someone",
          "posting a folded note into a mailbox slot"]),
 "6a8-32": dict(accent=EMO,
   hero="spinning a calm-down wheel of strategies when emotions overflow",
   mat="cardboard, a brad fastener, markers, scissors",
   steps=["a calm-down wheel with strategy pictures in sections",
          "spinning the arrow on a calm-down wheel",
          "a child breathing deeply, following the wheel"]),
 "6a8-33": dict(accent=NAT,
   hero="pressing leaves and flowers to build a nature collection album",
   mat="leaves and flowers, heavy books, absorbent paper, a notebook, glue",
   steps=["placing leaves between sheets of absorbent paper",
          "pressing leaves under a stack of heavy books",
          "gluing pressed leaves into a labeled notebook"]),
 "6a8-34": dict(accent=NAT,
   hero="measuring rain and wind with homemade weather instruments like a meteorologist",
   mat="a plastic bottle rain gauge, a ruler, cardboard and a stick for a vane, a calendar",
   steps=["a bottle rain gauge with a measuring scale outdoors",
          "a cardboard weather vane spinning in the wind",
          "noting the day's rainfall and wind on a calendar"]),
 "6a8-35": dict(accent=NAT,
   hero="building a bug hotel from sticks and pine cones to invite garden insects",
   mat="an open box, twigs, pine cones, dry leaves, cardboard tubes, string",
   steps=["filling a box with bundles of twigs and pine cones",
          "hanging a bug hotel in a quiet garden corner",
          "a little bug exploring a bug hotel"]),
 "6a8-36": dict(accent=NAT,
   hero="telling time by the shadow of a stick, like an ancient sundial",
   mat="a stick or pencil, a plate or patch of yard, stones or chalk, a clock",
   steps=["a stick standing upright in the center of a base",
          "marking where a stick's shadow falls each hour",
          "reading the time from a sundial shadow"]),

 # ---------------- 9 a 12 (existentes 01-12) ----------------
 "9a12-01": dict(accent=EXP,
   hero="doing marker chromatography, watching ink colors separate upward on a wet paper strip, curious",
   mat="coffee filters or paper towel strips, washable markers, glasses, water",
   steps=["drawing a thick marker dot near the bottom of a paper strip",
          "a paper strip hanging into a glass with a little water",
          "ink colors separating and climbing up a wet paper strip"]),
 "9a12-02": dict(accent=EXP,
   hero="building a homemade water clock from bottles, watching water drip to measure time",
   mat="two identical plastic bottles, a thin nail, tape, water, a permanent marker",
   steps=["making a tiny hole in a bottle cap with a nail",
          "stacking two bottles so water drips from one to the other",
          "marking water levels on a bottle to measure time"]),
 "9a12-03": dict(accent=JUE,
   hero="writing secret coded messages with a homemade paper cipher wheel at a desk",
   mat="paper and pencil, a ruler, cardboard for a cipher disk, a brad fastener",
   steps=["writing the alphabet with a shifted alphabet below it",
          "turning a homemade cardboard cipher wheel",
          "decoding a secret message letter by letter"]),
 "9a12-04": dict(accent=JUE,
   hero="setting up a homemade escape room with puzzles and small locked boxes for the family",
   mat="paper and pencil, envelopes and boxes for clues, a number padlock, hidden objects",
   steps=["writing a chain of puzzle clues on paper",
          "hiding a clue inside a small locked box",
          "solving a riddle to find a padlock code"]),
 "9a12-05": dict(accent=JUE,
   hero="designing a strategy board game from scratch with a board, pieces and rules",
   mat="cardboard for the board, a ruler and pencil, markers, caps as pieces, a dice",
   steps=["drawing a board of squares and zones on cardboard",
          "writing the rules of a homemade strategy game",
          "playing a test round and adjusting the rules"]),
 "9a12-06": dict(accent=REC,
   hero="moving through a challenging balance and obstacle course in the yard or hallway",
   mat="rope or paper tape, cushions, chairs and boxes, bottles, a stopwatch",
   steps=["a hand drawing an obstacle course plan with stations",
          "a child balancing along a rope line on the floor",
          "timing a run through a homemade obstacle course"]),
 "9a12-07": dict(accent=REC,
   hero="making juggling balls and learning to juggle three of them in the air",
   mat="sturdy balloons, rice or lentils, a cut bottle as a funnel, scissors",
   steps=["filling a balloon with rice using a funnel",
          "stretching a second balloon over a juggling ball",
          "juggling three homemade balls in the air"]),
 "9a12-08": dict(accent=EMO,
   hero="placing letters and small keepsakes into a time capsule box to open in a year, thoughtful",
   mat="a box or sealable jar, paper and pen, printed photos, small keepsakes",
   steps=["writing a letter to a future self",
          "placing photos and keepsakes into a time capsule box",
          "sealing and dating a time capsule box"]),
 "9a12-09": dict(accent=EMO,
   hero="a family pulling folded question slips from a jar and talking warmly together on the sofa",
   mat="a jar or cup, paper strips, pens, a comfy spot in a circle",
   steps=["writing thoughtful questions on paper strips",
          "folding question slips into a jar",
          "a family drawing a question and talking on a sofa"]),
 "9a12-10": dict(accent=ART,
   hero="drawing a comic page with empty panels and blank speech balloons, inventing a hero character",
   mat="sheets of paper, a ruler and pencil, an eraser, markers, a black pen",
   steps=["sketching a hero character in different poses",
          "drawing comic panels with a ruler on a page",
          "inking a comic page with speech balloons"]),
 "9a12-11": dict(accent=ART,
   hero="flipping a hand-drawn flipbook at the corner of a notebook, the little drawings coming to life",
   mat="a pad of sticky notes or small sheets, a pencil and eraser, a black pen, a clip",
   steps=["drawing the first frame at the corner of a small page",
          "tracing a slightly changed drawing on the next page",
          "flipping a flipbook so the drawing animates"]),
 "9a12-12": dict(accent=NAT,
   hero="planting and watering small herb seedlings in little pots and watching them grow",
   mat="pots or recycled containers with holes, planting soil, seeds or seedlings, water",
   steps=["filling a pot with soil almost to the brim",
          "planting small seeds into the soil",
          "watering a small potted herb on a sunny sill"]),

 # ---------------- 9 a 12 (nuevas 13-36) ----------------
 "9a12-13": dict(accent=EXP,
   hero="building a tiny vibrating robot from a motor, battery and cup that dances on the table",
   mat="a small toy motor, an AA battery holder, a plastic cup, markers, tape, clay",
   steps=["sticking a lump of clay off-center on a motor shaft",
          "connecting a small motor to a battery with wires",
          "a little cup robot with marker legs scribbling on paper"]),
 "9a12-14": dict(accent=EXP,
   hero="lighting a small bulb with a battery and wires, the spark of electronics",
   mat="a battery, a small bulb or LED, wires or foil, tape, a paper-clip switch",
   steps=["connecting a wire from a battery to a small bulb",
          "a small bulb lighting up in a simple circuit",
          "a paper-clip switch turning a bulb on and off"]),
 "9a12-15": dict(accent=EXP,
   hero="pumping air into a water bottle rocket and watching it blast off outdoors",
   mat="a plastic bottle, a cork, a pump with a needle, water, a launch stand",
   steps=["filling a bottle one third with water",
          "sealing a bottle with a cork and pump needle",
          "a bottle rocket blasting up into the sky outdoors"]),
 "9a12-16": dict(accent=EXP,
   hero="stacking colorful liquid layers that will not mix, like a rainbow in a glass",
   mat="a tall clear glass, honey, dish soap, colored water, oil, colored alcohol, a spoon",
   steps=["pouring honey into the bottom of a tall glass",
          "layering colored liquids gently down a spoon",
          "stacked colorful liquid layers in a tall glass"]),
 "9a12-17": dict(accent=EXP,
   hero="writing a secret message that appears only with heat",
   mat="lemon juice, a brush or cotton swab, white paper, a heat source",
   steps=["writing on paper with a cotton swab and lemon juice",
          "an invisible dried message on white paper",
          "a hidden message turning brown near gentle heat"]),
 "9a12-18": dict(accent=EXP,
   hero="testing how much weight a paper bridge can hold, designing and improving it",
   mat="sheets of paper, two books as supports, coins as weights, tape",
   steps=["a flat paper bridge resting between two books",
          "stacking coins on a paper bridge until it bends",
          "an accordion-folded paper bridge holding more coins"]),
 "9a12-19": dict(accent=REC,
   hero="launching pom-poms as far as possible with a homemade craft-stick catapult",
   mat="craft sticks, rubber bands, a bottle cap or small spoon, pom-poms",
   steps=["binding craft sticks together with rubber bands",
          "a craft-stick catapult loaded with a pom-pom",
          "a pom-pom flying from a launched catapult"]),
 "9a12-20": dict(accent=REC,
   hero="finding hidden points around the house with a homemade map and clues",
   mat="paper for a map, clue cards, pencils, a stopwatch",
   steps=["drawing a simple map with marked points",
          "finding a hidden clue card at a checkpoint",
          "following a map to the next point"]),
 "9a12-21": dict(accent=REC,
   hero="jumping rope with routines and songs, beating their own record",
   mat="a jump rope, an open space, music",
   steps=["a child mid-jump over a swinging rope",
          "two children turning a long rope for another to jump",
          "crossing the arms in a jump-rope trick"]),
 "9a12-22": dict(accent=JUE,
   hero="racing to fill word categories from a single letter: name, animal, color",
   mat="paper and pencils, a category table",
   steps=["a category table with columns drawn on paper",
          "writing words quickly in category columns",
          "comparing answers and scoring around a table"]),
 "9a12-23": dict(accent=JUE,
   hero="guessing a character stuck on the forehead with yes-or-no questions",
   mat="cards, pencils, tape or a headband",
   steps=["writing a character name on a card",
          "a card stuck on a child's forehead",
          "children asking yes-or-no questions, thinking"]),
 "9a12-24": dict(accent=JUE,
   hero="playing checkers on a handmade board, planning moves ahead",
   mat="cardboard for the board, markers, caps in two colors as pieces",
   steps=["drawing an eight-by-eight checkerboard on cardboard",
          "setting up checker pieces on the dark squares",
          "jumping over a piece to capture it in checkers"]),
 "9a12-25": dict(accent=JUE,
   hero="solving sudokus and puzzles to train the brain like a gym",
   mat="printed easy sudokus, puzzles and mazes, a pencil and eraser",
   steps=["an easy sudoku grid with some numbers filled in",
          "a hand penciling a number into a sudoku",
          "solving a maze puzzle with a pencil"]),
 "9a12-26": dict(accent=ART,
   hero="moving figures frame by frame to make a stop-motion movie on a phone",
   mat="a phone or tablet on a stand, a stop-motion app, toys or clay, a backdrop",
   steps=["a phone on a stand pointed at toy figures",
          "moving a clay figure a tiny bit between photos",
          "playing back a stop-motion animation on a screen"]),
 "9a12-27": dict(accent=ART,
   hero="drawing repeating patterns from the center to focus and calm the mind",
   mat="paper, a compass or cup, markers, a ruler",
   steps=["drawing concentric circles as a mandala base",
          "repeating a pattern around a mandala ring",
          "coloring a finished symmetrical mandala"]),
 "9a12-28": dict(accent=ART,
   hero="putting on a shadow puppet show with cardboard cutouts and a flashlight",
   mat="cardboard for silhouettes, sticks, a white sheet, a flashlight, scissors",
   steps=["cutting a character silhouette from cardboard",
          "taping a stick to a cardboard silhouette",
          "shadow puppets projected on a lit white sheet"]),
 "9a12-29": dict(accent=ART,
   hero="tying, dyeing and revealing a unique pattern on their own shirt",
   mat="a white cotton shirt, fabric dye, rubber bands, gloves, a tub",
   steps=["a white shirt twisted and bound with rubber bands",
          "applying colorful dye to a bound shirt",
          "unfolding a shirt to reveal a tie-dye spiral"]),
 "9a12-30": dict(accent=EMO,
   hero="writing a letter to their future self to open in a year",
   mat="paper and pencil, an envelope, stickers",
   steps=["writing a letter to a future self at a desk",
          "sealing a letter in an envelope with a date",
          "placing a sealed letter in a safe keepsake spot"]),
 "9a12-31": dict(accent=EMO,
   hero="making a vision board collage of goals and inspiring images",
   mat="a large card, magazines, photos, scissors, glue, markers",
   steps=["cutting inspiring images from magazines",
          "arranging images into a vision board collage",
          "a finished goals collage hung on a wall"]),
 "9a12-32": dict(accent=EMO,
   hero="writing how they feel in an emotions journal to understand themselves",
   mat="a notebook, colored pencils, a feelings reference list",
   steps=["a decorated emotions journal with a feelings list",
          "writing the day's main emotion in a journal",
          "coloring in a feeling on a journal page"]),
 "9a12-33": dict(accent=NAT,
   hero="turning food scraps into compost and discovering how nature recycles",
   mat="a bin with a lid, fruit and vegetable scraps, dry leaves, soil, a tool",
   steps=["layering soil and dry leaves in a compost bin",
          "adding chopped fruit and vegetable scraps",
          "stirring dark crumbly finished compost"]),
 "9a12-34": dict(accent=NAT,
   hero="finding constellations with a star map on a clear night",
   mat="a star map or astronomy app, a red-covered flashlight, a blanket, a coat",
   steps=["lying on a blanket looking up at a starry sky",
          "holding a star map under a red flashlight",
          "tracing a constellation in the night sky"]),
 "9a12-35": dict(accent=NAT,
   hero="building a filter with stones and sand to see muddy water get clearer",
   mat="a cut plastic bottle, stones, sand, charcoal, cotton, muddy water, a glass",
   steps=["layering cotton, charcoal, sand and stones in a bottle",
          "pouring muddy water into the top of a filter",
          "comparing muddy and clearer filtered water in two glasses"]),
 "9a12-36": dict(accent=NAT,
   hero="watching birds and recording each species like a naturalist",
   mat="a notebook and pencils, binoculars, a bird guide or app",
   steps=["watching a bird in a tree through binoculars",
          "sketching a bird in a field notebook",
          "identifying a bird in a guide book"]),
}
